// tools/crawler_source.dart
// 크롤러의 단일 진실 소스 (Single Source of Truth)
// IDE에서 직접 편집 가능. merge.dart로 빌드 후 사용.
//
// figma_temp_crawler.dart (auto-generated by export_figma_layout.dart)
// Schema v2: explicit layoutMode, childLayout, containerLayout, visual

import 'dart:convert';
import 'dart:math' as math;
import 'dart:ui' as ui;
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';

const figmaCrawlerVersion = '0.2.0';

/// =======================================================
/// 0. 유틸 & 전역 상태
/// =======================================================

String? _colorToHex(Color? color) {
  if (color == null) return null;
  return '#' + color.value.toRadixString(16).padLeft(8, '0');
}

class DesignInfo {
  final Color? backgroundColor;
  final Color? borderColor;
  final double? borderWidth;
  final dynamic borderRadius; // double (uniform) or Map {tl,tr,bl,br}
  final double? elevation;
  final bool isTextField;
  final bool isDivider;
  final double? borderTopWidth;
  final double? borderRightWidth;
  final double? borderBottomWidth;
  final double? borderLeftWidth;
  final bool clipsContent;

  DesignInfo({
    this.backgroundColor,
    this.borderColor,
    this.borderWidth,
    this.borderRadius,
    this.elevation,
    this.isTextField = false,
    this.isDivider = false,
    this.borderTopWidth,
    this.borderRightWidth,
    this.borderBottomWidth,
    this.borderLeftWidth,
    this.clipsContent = false,
  });
}

final Map<RenderObject, DesignInfo> _designInfoByRenderObject = {};
final Set<RenderObject> _svgBoxTargets = {};
final Map<RenderObject, String> _imageDataByNode = {};
final Set<RenderObject> _customPaintCaptures = {};

/// 이미지/아이콘 캡처 해상도 배율 (CLI --pixel-ratio 플래그로 제어)
double _capturePixelRatio = 3.0;
final Map<RenderObject, String> _widgetNameByRenderObject = {};
final Map<RenderObject, double> _blurInfoByRenderObject = {};
final Map<RenderObject, double> _rotationByRenderObject = {};
final Map<RenderObject, ShaderMask> _shaderMaskWidgets = {};
final Map<RenderObject, Map<String, dynamic>> _shaderMaskGradients = {};
final Map<RenderObject, CustomPainter> _customPainterByRO = {};
final Map<RenderObject, CustomClipper<Path>> _clipperByRenderObject = {};
final Map<RenderObject, List<Map<String, double>>> _clipPathPoints = {};
final Map<RenderObject, String> _boxFitByRenderObject = {};
final Set<RenderObject> _rotatedBoxNodes = {};
String? _asyncExportResult;
bool _asyncExportBusy = false;

void _markCaptureRecursive(RenderObject ro) {
  _customPaintCaptures.add(ro);
  ro.visitChildren((child) => _markCaptureRecursive(child));
}

/// RenderShaderMask의 public shaderCallback getter를 dynamic dispatch로 접근,
/// 사각형에 shader를 직접 칠한 뒤 픽셀 샘플링으로 gradient 추출
Future<void> _extractShaderMaskGradients(RenderObject root) async {
  final List<RenderBox> nodes = [];
  void find(RenderObject ro) {
    final name = ro.runtimeType.toString();
    if (name.contains('ShaderMask') && ro is RenderBox && ro.hasSize) {
      nodes.add(ro);
    }
    ro.visitChildren(find);
  }

  find(root);
  debugPrint('[ShaderMask] found ${nodes.length} nodes');

  for (final node in nodes) {
    try {
      final w = node.size.width;
      final h = node.size.height;
      if (w <= 0 || h <= 0) continue;

      // dynamic dispatch로 shaderCallback 접근
      final dynamic dynNode = node;
      final Function callback = dynNode.shaderCallback as Function;
      final rect = Offset.zero & Size(w, h);
      final shader = callback(rect) as ui.Shader;
      debugPrint('[ShaderMask] got shader from callback, size=${w}x${h}');

      // 사각형 전체를 shader로 칠해서 캡처 (텍스트 형태가 아닌 full rect)
      final sw = w.ceil().clamp(4, 64);
      final sh = h.ceil().clamp(4, 64);
      final recorder = ui.PictureRecorder();
      final canvas = Canvas(recorder);
      canvas.drawRect(
        Rect.fromLTWH(0, 0, sw.toDouble(), sh.toDouble()),
        Paint()..shader = shader,
      );
      final picture = recorder.endRecording();
      final image = await picture.toImage(sw, sh);
      final byteData = await image.toByteData(
        format: ui.ImageByteFormat.rawRgba,
      );
      image.dispose();
      if (byteData == null) {
        debugPrint('[ShaderMask] byteData null');
        continue;
      }

      Color getPixel(int x, int y) {
        x = x.clamp(0, sw - 1);
        y = y.clamp(0, sh - 1);
        final off = (y * sw + x) * 4;
        return Color.fromARGB(
          byteData.getUint8(off + 3),
          byteData.getUint8(off),
          byteData.getUint8(off + 1),
          byteData.getUint8(off + 2),
        );
      }

      double colorDist(Color a, Color b) =>
          ((a.red - b.red).abs() +
                  (a.green - b.green).abs() +
                  (a.blue - b.blue).abs())
              .toDouble();

      // 방향 판별
      const n = 6;
      double hVar = 0, vVar = 0;
      for (int i = 1; i < n; i++) {
        hVar += colorDist(
          getPixel(((i - 1) * (sw - 1) ~/ (n - 1)), sh ~/ 2),
          getPixel((i * (sw - 1) ~/ (n - 1)), sh ~/ 2),
        );
        vVar += colorDist(
          getPixel(sw ~/ 2, ((i - 1) * (sh - 1) ~/ (n - 1))),
          getPixel(sw ~/ 2, (i * (sh - 1) ~/ (n - 1))),
        );
      }
      final bool isVert = vVar >= hVar;
      debugPrint('[ShaderMask] hVar=$hVar vVar=$vVar isVert=$isVert');

      // 색상 샘플링
      const sc = 10;
      final colors = <String>[];
      final stops = <double>[];
      for (int i = 0; i < sc; i++) {
        final t = i / (sc - 1);
        final c = isVert
            ? getPixel(sw ~/ 2, (t * (sh - 1)).round())
            : getPixel((t * (sw - 1)).round(), sh ~/ 2);
        colors.add(_colorToHex(c)!);
        stops.add(t);
      }

      // 간소화: 연속 중복 제거
      final sC = <String>[colors.first];
      final sS = <double>[stops.first];
      for (int i = 1; i < colors.length - 1; i++) {
        if (colors[i] != colors[i - 1] || colors[i] != colors[i + 1]) {
          sC.add(colors[i]);
          sS.add(stops[i]);
        }
      }
      sC.add(colors.last);
      sS.add(stops.last);

      final gradient = <String, dynamic>{
        'type': 'linear',
        'colors': sC,
        'stops': sS,
        'begin': {'x': isVert ? 0.5 : 0.0, 'y': isVert ? 0.0 : 0.5},
        'end': {'x': isVert ? 0.5 : 1.0, 'y': isVert ? 1.0 : 0.5},
      };
      debugPrint('[ShaderMask] gradient colors: $sC');

      void mapAll(RenderObject obj) {
        _shaderMaskGradients[obj] = gradient;
        obj.visitChildren(mapAll);
      }

      node.visitChildren(mapAll);
    } catch (e, st) {
      debugPrint('[ShaderMask] ERROR: $e\n$st');
    }
  }
}

