#!/usr/bin/env dart
// tools/export_figma_layout.dart
//
// ⚠️  이 파일을 직접 실행하지 마세요!
// merge.dart로 generated_export_figma_layout.dart를 생성한 후 실행하세요:
//   dart tools/merge.dart
//   dart tools/generated_export_figma_layout.dart
//
// Pure Dart CLI — 외부 패키지 의존성 0개, 크롤러 소스 내장 (빌드 시 치환)
// 실행 중인 Flutter 앱에서 레이아웃 JSON을 추출합니다.
//
// Android Studio External Tool 설정:
//   Program:           dart
//   Arguments:         /path/to/tools/generated_export_figma_layout.dart
//   Working directory: $ProjectFileDir$

import 'dart:async';
import 'dart:convert';
import 'dart:io';

// =============================================================
// 임베디드 크롤러 소스 (figma_exporter_inject.dart)
// =============================================================

const _crawlerSource = r"""//
// figma_temp_crawler.dart (auto-generated by export_figma_layout.dart)
// Schema v2: explicit layoutMode, childLayout, containerLayout, visual

import 'dart:convert';
import 'dart:math' as math;
import 'dart:ui' as ui;
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';

/// =======================================================
/// 0. 유틸 & 전역 상태
/// =======================================================

String? _colorToHex(Color? color) {
  if (color == null) return null;
  return '#' + color.value.toRadixString(16).padLeft(8, '0');
}

class DesignInfo {
  final Color? backgroundColor;
  final Color? borderColor;
  final double? borderWidth;
  final double? borderRadius;
  final double? elevation;
  final bool isTextField;
  final bool isDivider;
  final double? borderTopWidth;
  final double? borderRightWidth;
  final double? borderBottomWidth;
  final double? borderLeftWidth;

  DesignInfo({
    this.backgroundColor,
    this.borderColor,
    this.borderWidth,
    this.borderRadius,
    this.elevation,
    this.isTextField = false,
    this.isDivider = false,
    this.borderTopWidth,
    this.borderRightWidth,
    this.borderBottomWidth,
    this.borderLeftWidth,
  });
}

final Map<RenderObject, DesignInfo> _designInfoByRenderObject = {};
final Set<RenderObject> _svgBoxTargets = {};
final Map<RenderObject, String> _imageDataByNode = {};
final Set<RenderObject> _customPaintCaptures = {};
final Map<RenderObject, String> _widgetNameByRenderObject = {};
final Map<RenderObject, double> _blurInfoByRenderObject = {};
final Map<RenderObject, double> _rotationByRenderObject = {};
final Map<RenderObject, ShaderMask> _shaderMaskWidgets = {};
final Map<RenderObject, Map<String, dynamic>> _shaderMaskGradients = {};
final Map<RenderObject, CustomPainter> _customPainterByRO = {};
String? _asyncExportResult;
bool _asyncExportBusy = false;

void _markCaptureRecursive(RenderObject ro) {
  _customPaintCaptures.add(ro);
  ro.visitChildren((child) => _markCaptureRecursive(child));
}

/// RenderShaderMask의 public shaderCallback getter를 dynamic dispatch로 접근,
/// 사각형에 shader를 직접 칠한 뒤 픽셀 샘플링으로 gradient 추출
Future<void> _extractShaderMaskGradients(RenderObject root) async {
  final List<RenderBox> nodes = [];
  void find(RenderObject ro) {
    final name = ro.runtimeType.toString();
    if (name.contains('ShaderMask') && ro is RenderBox && ro.hasSize) {
      nodes.add(ro);
    }
    ro.visitChildren(find);
  }
  find(root);
  debugPrint('[ShaderMask] found ${nodes.length} nodes');

  for (final node in nodes) {
    try {
      final w = node.size.width;
      final h = node.size.height;
      if (w <= 0 || h <= 0) continue;

      // dynamic dispatch로 shaderCallback 접근
      final dynamic dynNode = node;
      final Function callback = dynNode.shaderCallback as Function;
      final rect = Offset.zero & Size(w, h);
      final shader = callback(rect) as ui.Shader;
      debugPrint('[ShaderMask] got shader from callback, size=${w}x${h}');

      // 사각형 전체를 shader로 칠해서 캡처 (텍스트 형태가 아닌 full rect)
      final sw = w.ceil().clamp(4, 64);
      final sh = h.ceil().clamp(4, 64);
      final recorder = ui.PictureRecorder();
      final canvas = Canvas(recorder);
      canvas.drawRect(
        Rect.fromLTWH(0, 0, sw.toDouble(), sh.toDouble()),
        Paint()..shader = shader,
      );
      final picture = recorder.endRecording();
      final image = await picture.toImage(sw, sh);
      final byteData = await image.toByteData(format: ui.ImageByteFormat.rawRgba);
      image.dispose();
      if (byteData == null) {
        debugPrint('[ShaderMask] byteData null');
        continue;
      }

      Color getPixel(int x, int y) {
        x = x.clamp(0, sw - 1);
        y = y.clamp(0, sh - 1);
        final off = (y * sw + x) * 4;
        return Color.fromARGB(
          byteData.getUint8(off + 3),
          byteData.getUint8(off),
          byteData.getUint8(off + 1),
          byteData.getUint8(off + 2),
        );
      }

      double colorDist(Color a, Color b) =>
          ((a.red - b.red).abs() + (a.green - b.green).abs() + (a.blue - b.blue).abs()).toDouble();

      // 방향 판별
      const n = 6;
      double hVar = 0, vVar = 0;
      for (int i = 1; i < n; i++) {
        hVar += colorDist(
          getPixel(((i - 1) * (sw - 1) ~/ (n - 1)), sh ~/ 2),
          getPixel((i * (sw - 1) ~/ (n - 1)), sh ~/ 2),
        );
        vVar += colorDist(
          getPixel(sw ~/ 2, ((i - 1) * (sh - 1) ~/ (n - 1))),
          getPixel(sw ~/ 2, (i * (sh - 1) ~/ (n - 1))),
        );
      }
      final bool isVert = vVar >= hVar;
      debugPrint('[ShaderMask] hVar=$hVar vVar=$vVar isVert=$isVert');

      // 색상 샘플링
      const sc = 10;
      final colors = <String>[];
      final stops = <double>[];
      for (int i = 0; i < sc; i++) {
        final t = i / (sc - 1);
        final c = isVert
            ? getPixel(sw ~/ 2, (t * (sh - 1)).round())
            : getPixel((t * (sw - 1)).round(), sh ~/ 2);
        colors.add(_colorToHex(c)!);
        stops.add(t);
      }

      // 간소화: 연속 중복 제거
      final sC = <String>[colors.first];
      final sS = <double>[stops.first];
      for (int i = 1; i < colors.length - 1; i++) {
        if (colors[i] != colors[i - 1] || colors[i] != colors[i + 1]) {
          sC.add(colors[i]);
          sS.add(stops[i]);
        }
      }
      sC.add(colors.last);
      sS.add(stops.last);

      final gradient = <String, dynamic>{
        'type': 'linear',
        'colors': sC,
        'stops': sS,
        'begin': {'x': isVert ? 0.5 : 0.0, 'y': isVert ? 0.0 : 0.5},
        'end': {'x': isVert ? 0.5 : 1.0, 'y': isVert ? 1.0 : 0.5},
      };
      debugPrint('[ShaderMask] gradient colors: $sC');

      void mapAll(RenderObject obj) {
        _shaderMaskGradients[obj] = gradient;
        obj.visitChildren(mapAll);
      }
      node.visitChildren(mapAll);
    } catch (e, st) {
      debugPrint('[ShaderMask] ERROR: $e\n$st');
    }
  }
}

/// =======================================================
/// 0.5 Pre-capture: 이미지/아이콘 → base64 (async)
/// =======================================================

Future<void> _preCaptureImages(RenderObject node) async {
  // RenderImage → 축소 후 PNG 인코딩 (최대 512px)
  if (node is RenderImage) {
    try {
      final ui.Image? img = node.image;
      if (img != null) {
        final maxDim = 512;
        int targetW = img.width;
        int targetH = img.height;
        if (targetW > maxDim || targetH > maxDim) {
          final scale = maxDim / (targetW > targetH ? targetW : targetH);
          targetW = (targetW * scale).ceil();
          targetH = (targetH * scale).ceil();
        }
        final recorder = ui.PictureRecorder();
        final canvas = Canvas(recorder);
        canvas.drawImageRect(
          img,
          Rect.fromLTWH(0, 0, img.width.toDouble(), img.height.toDouble()),
          Rect.fromLTWH(0, 0, targetW.toDouble(), targetH.toDouble()),
          Paint(),
        );
        final picture = recorder.endRecording();
        final resized = await picture.toImage(targetW, targetH);
        final byteData = await resized.toByteData(
          format: ui.ImageByteFormat.png,
        );
        if (byteData != null) {
          _imageDataByNode[node] = base64Encode(byteData.buffer.asUint8List());
        }
      }
    } catch (_) {}
  }

  // MaterialIcons → TextPainter → PictureRecorder → toImage()
  if (node is RenderParagraph) {
    try {
      final span = node.text;
      if (span is TextSpan &&
          span.style?.fontFamily?.contains('MaterialIcons') == true) {
        final recorder = ui.PictureRecorder();
        final canvas = Canvas(
          recorder,
          Rect.fromLTWH(0, 0, node.size.width, node.size.height),
        );
        final painter = TextPainter(
          text: span,
          textDirection: TextDirection.ltr,
        );
        painter.layout();
        painter.paint(canvas, Offset.zero);
        final picture = recorder.endRecording();
        final img = await picture.toImage(
          node.size.width.ceil(),
          node.size.height.ceil(),
        );
        final byteData = await img.toByteData(format: ui.ImageByteFormat.png);
        if (byteData != null) {
          _imageDataByNode[node] = base64Encode(byteData.buffer.asUint8List());
        }
      }
    } catch (_) {}
  }

  // CustomPaint with painter → 투명 배경에 painter만 직접 paint
  if (node is RenderBox &&
      _customPainterByRO.containsKey(node) &&
      !_imageDataByNode.containsKey(node)) {
    try {
      final painter = _customPainterByRO[node]!;
      final w = node.size.width;
      final h = node.size.height;
      if (w > 0 && h > 0) {
        const double pr = 2.0;
        final outW = (w * pr).round();
        final outH = (h * pr).round();
        final recorder = ui.PictureRecorder();
        final canvas = Canvas(recorder, Rect.fromLTWH(0, 0, outW.toDouble(), outH.toDouble()));
        canvas.scale(pr);
        painter.paint(canvas, Size(w, h));
        final picture = recorder.endRecording();
        final img = await picture.toImage(outW, outH);
        final byteData = await img.toByteData(format: ui.ImageByteFormat.png);
        img.dispose();
        if (byteData != null) {
          _imageDataByNode[node] = base64Encode(byteData.buffer.asUint8List());
        }
      }
    } catch (e) {
      debugPrint('[CustomPainter] direct paint failed: $e');
    }
  }

  // Checkbox / Switch 등 → 가장 가까운 RepaintBoundary에서 crop 캡처
  // 실제 컴포넌트보다 사방 2px 넓게 캡처하여 overflow paint(리플/그림자) 포함
  // 출력 PNG는 항상 (w+4)x(h+4) 크기, 소스 부족 영역은 투명
  if (node is RenderBox &&
      _customPaintCaptures.contains(node) &&
      !_imageDataByNode.containsKey(node)) {
    try {
      final w = node.size.width;
      final h = node.size.height;
      if (w > 0 && h > 0) {
        const double pr = 2.0;
        const double pad = 4.0;
        // 충분히 큰 RepaintBoundary를 찾음 (노드보다 사방 pad 이상 큰 것)
        RenderObject? ancestor = node.parent;
        RenderRepaintBoundary? bestBoundary;
        while (ancestor != null) {
          if (ancestor is RenderRepaintBoundary) {
            bestBoundary = ancestor;
            if (ancestor.size.width >= w + pad * 2 &&
                ancestor.size.height >= h + pad * 2) {
              break;
            }
          }
          ancestor = ancestor.parent;
        }
        ancestor = bestBoundary;
        if (ancestor is RenderRepaintBoundary) {
          final img = await ancestor.toImage(pixelRatio: pr);
          final nodeOffset = node.localToGlobal(Offset.zero);
          final boundaryOffset = (ancestor as RenderBox).localToGlobal(
            Offset.zero,
          );
          // 출력 이미지 크기 (항상 고정)
          final outW = ((w + pad * 2) * pr).round();
          final outH = ((h + pad * 2) * pr).round();
          // 소스 crop 영역 (pixel 좌표)
          final rawSrcX = (nodeOffset.dx - boundaryOffset.dx - pad) * pr;
          final rawSrcY = (nodeOffset.dy - boundaryOffset.dy - pad) * pr;
          // 클램프: 소스 이미지 밖이면 잘라내고, 대상 오프셋 조정
          final srcX = rawSrcX.clamp(0.0, img.width.toDouble());
          final srcY = rawSrcY.clamp(0.0, img.height.toDouble());
          final dstX = srcX - rawSrcX; // 소스가 잘린만큼 대상에서 오프셋
          final dstY = srcY - rawSrcY;
          final srcW = (outW.toDouble() - dstX).clamp(
            0.0,
            img.width.toDouble() - srcX,
          );
          final srcH = (outH.toDouble() - dstY).clamp(
            0.0,
            img.height.toDouble() - srcY,
          );
          if (srcW > 0 && srcH > 0) {
            final recorder = ui.PictureRecorder();
            final canvas = Canvas(
              recorder,
              Rect.fromLTWH(0, 0, outW.toDouble(), outH.toDouble()),
            );
            // 배경 투명 (기본값)
            canvas.drawImageRect(
              img,
              Rect.fromLTWH(srcX, srcY, srcW, srcH),
              Rect.fromLTWH(dstX, dstY, srcW, srcH),
              Paint(),
            );
            final picture = recorder.endRecording();
            final cropped = await picture.toImage(outW, outH);
            final byteData = await cropped.toByteData(
              format: ui.ImageByteFormat.png,
            );
            if (byteData != null) {
              _imageDataByNode[node] = base64Encode(
                byteData.buffer.asUint8List(),
              );
            }
          }
        }
      }
    } catch (_) {}
  }

  // 자식 재귀 (visitChildren은 sync callback → 리스트 수집 후 순회)
  final children = <RenderObject>[];
  node.visitChildren((child) => children.add(child));
  for (final child in children) {
    await _preCaptureImages(child);
  }
}

/// =======================================================
/// 1. Element 트리 순회해서 위젯 레벨 디자인 정보 수집
/// =======================================================

void _collectDesignInfoFromElements(Element element) {
  final widget = element.widget;

  if (widget is InputDecorator) {
    final InputDecoration deco = widget.decoration;
    Color? bg;
    Color? borderColor;
    double? borderWidth;
    double? radius;

    if (deco.filled == true) {
      bg = deco.fillColor;
    }

    final InputBorder? border =
        deco.enabledBorder ?? deco.focusedBorder ?? deco.border;

    if (border is OutlineInputBorder) {
      final side = border.borderSide;
      borderColor = side.color;
      borderWidth = side.width;
      final br = border.borderRadius;
      if (br is BorderRadius) {
        radius = br.topLeft.x;
      }
    }

    final ro = element.renderObject;
    if (ro != null && (bg != null || borderColor != null || radius != null)) {
      _designInfoByRenderObject[ro] = DesignInfo(
        backgroundColor: bg,
        borderColor: borderColor,
        borderWidth: borderWidth,
        borderRadius: radius,
        isTextField: true,
      );
    }
  }

  if (widget is Divider) {
    final ro = element.renderObject;
    if (ro != null && widget.color != null) {
      _designInfoByRenderObject[ro] = DesignInfo(
        backgroundColor: widget.color,
        isDivider: true,
      );
    }
  }

  if (widget is Container) {
    final deco = widget.decoration;
    Color? bg;
    Color? borderColor;
    double? borderWidth;
    double? radius;
    double? borderTopW, borderRightW, borderBottomW, borderLeftW;

    if (deco is BoxDecoration) {
      bg = deco.color;
      final border = deco.border;
      if (border is Border) {
        final sides = [border.top, border.right, border.bottom, border.left];
        BorderSide? best;
        for (final s in sides) {
          if (best == null || s.width > best.width) best = s;
        }
        if (best != null && best.width > 0) {
          borderColor = best.color;
          borderWidth = best.width;
        }
        final uniform = sides.every(
          (s) => s.width == sides[0].width && s.color == sides[0].color,
        );
        if (!uniform) {
          borderTopW = border.top.width;
          borderRightW = border.right.width;
          borderBottomW = border.bottom.width;
          borderLeftW = border.left.width;
        }
      }
      final br = deco.borderRadius;
      if (br is BorderRadius) {
        radius = br.topLeft.x;
      }
    }

    final ro = element.renderObject;
    if (ro != null && (bg != null || borderColor != null)) {
      _designInfoByRenderObject[ro] = DesignInfo(
        backgroundColor: bg,
        borderColor: borderColor,
        borderWidth: borderWidth,
        borderRadius: radius,
        borderTopWidth: borderTopW,
        borderRightWidth: borderRightW,
        borderBottomWidth: borderBottomW,
        borderLeftWidth: borderLeftW,
      );
    }
  }

  if (widget.runtimeType.toString().contains('SvgPicture')) {
    final ro = element.renderObject;
    if (ro != null) {
      _svgBoxTargets.add(ro);
    }
  }

  // Material 위젯 (OutlinedButton, ElevatedButton 등의 보더)
  // _ShapeBorderPaint(CustomPaint)로 그려지는 보더는 render tree에서 추출 불가
  // → element tree에서 Material.shape.side를 직접 추출
  if (widget is Material && widget.shape != null) {
    final shape = widget.shape;
    if (shape is OutlinedBorder) {
      final side = shape.side;
      if (side.width > 0 && side.style == BorderStyle.solid) {
        double? radius;
        if (shape is RoundedRectangleBorder) {
          final br = shape.borderRadius;
          if (br is BorderRadius) {
            radius = br.topLeft.x;
          }
        }
        final ro = element.renderObject;
        if (ro != null) {
          // 기존 DesignInfo가 있으면 덮어쓰지 않고, 없을 때만 등록
          if (!_designInfoByRenderObject.containsKey(ro)) {
            _designInfoByRenderObject[ro] = DesignInfo(
              borderColor: side.color,
              borderWidth: side.width,
              borderRadius: radius,
            );
          }
        }
      }
    }
  }

  // 전용 위젯 이름 태깅
  final widgetTypeName = widget.runtimeType.toString();
  const namedWidgets = {'NavigationToolbar', 'BottomNavigationBar', 'Scaffold'};
  if (namedWidgets.contains(widgetTypeName)) {
    final ro = element.renderObject;
    if (ro != null) {
      _widgetNameByRenderObject[ro] = widgetTypeName;
    }
  }

  // Checkbox / Switch → renderObject와 하위 자식 모두 캡처 대상 등록
  const captureWidgets = {
    'Checkbox', 'Switch', 'CupertinoSwitch',
    'Slider', 'CircularProgressIndicator', 'LinearProgressIndicator',
    'ChoiceChip', 'FilterChip', 'InputChip', 'ActionChip',
  };
  if (captureWidgets.contains(widgetTypeName)) {
    final ro = element.renderObject;
    if (ro != null) {
      _markCaptureRecursive(ro);
    }
  }

  // ShaderMask → render tree 순회로 감지 (async phase에서 처리)

  // CustomPaint with painter → painter를 직접 빈 캔버스에 paint (투명 배경)
  // child가 없는 leaf CustomPaint만 캡처 (순수 장식용)
  // Flutter 내부 CustomPaint(child 있음: ink effect, indicator 등)는 스킵 → 자연 분해
  if (widgetTypeName == 'CustomPaint') {
    final cp = widget as CustomPaint;
    if (cp.painter != null && cp.child == null) {
      final ro = element.renderObject;
      if (ro != null) {
        _customPainterByRO[ro] = cp.painter!;
        _markCaptureRecursive(ro);
      }
    }
  }

  // BackdropFilter → blur sigma 추출
  if (widget is BackdropFilter) {
    try {
      final filter = widget.filter;
      final filterStr = filter.toString();
      // ImageFilter.blur(sigmaX: 10.0, sigmaY: 10.0, ...)
      final sigmaMatch = RegExp(r'sigmaX:\s*([\d.]+)').firstMatch(filterStr);
      if (sigmaMatch != null) {
        final sigma = double.tryParse(sigmaMatch.group(1)!) ?? 0;
        if (sigma > 0) {
          final ro = element.renderObject;
          if (ro != null) {
            _blurInfoByRenderObject[ro] = sigma;
          }
        }
      }
    } catch (_) {}
  }

  // Transform.rotate → angle 추출
  if (widget is Transform) {
    try {
      final ro = element.renderObject;
      if (ro != null) {
        // Transform widget의 transform Matrix4에서 rotation 추출
        final t = widget.transform;
        final sinVal = t.entry(1, 0);
        final cosVal = t.entry(0, 0);
        final radians = math.atan2(sinVal, cosVal);
        if (radians.abs() > 0.001) {
          final degrees = radians * 180.0 / math.pi;
          _rotationByRenderObject[ro] = degrees;
          debugPrint('[Transform] captured rotation=${degrees.toStringAsFixed(2)}° for $ro');
        }
      }
    } catch (e) {
      debugPrint('[Transform] angle extraction failed: $e');
    }
  }

  element.visitChildren(_collectDesignInfoFromElements);
}

/// =======================================================
/// 2. 헬퍼: visual 속성 추출
/// =======================================================

/// borderRadius 문자열에서 숫자 추출
double? _parseBorderRadius(dynamic br) {
  if (br == null) return null;
  final s = br.toString();
  if (s.contains('zero')) return 0.0;
  final m = RegExp(r'\d+\.?\d*').firstMatch(s);
  if (m != null) return double.tryParse(m.group(0)!);
  return double.tryParse(s);
}

/// gradient 추출 (LinearGradient, RadialGradient, SweepGradient)
Map<String, dynamic>? _extractGradient(dynamic gradient) {
  if (gradient == null) return null;
  final colors = <String>[];
  final stops = <double>[];
  try {
    final colorList = gradient.colors as List<Color>;
    for (final c in colorList) {
      colors.add(_colorToHex(c)!);
    }
    final stopList = gradient.stops as List<double>?;
    if (stopList != null) {
      stops.addAll(stopList);
    } else {
      for (int i = 0; i < colors.length; i++) {
        stops.add(i / (colors.length - 1));
      }
    }
  } catch (_) { return null; }

  final map = <String, dynamic>{
    'colors': colors,
    'stops': stops,
  };

  final typeName = gradient.runtimeType.toString();
  if (typeName.contains('LinearGradient')) {
    map['type'] = 'linear';
    try {
      final begin = gradient.begin as Alignment;
      final end = gradient.end as Alignment;
      map['begin'] = {'x': (begin.x + 1) / 2, 'y': (begin.y + 1) / 2};
      map['end'] = {'x': (end.x + 1) / 2, 'y': (end.y + 1) / 2};
    } catch (_) {
      map['begin'] = {'x': 0.5, 'y': 0.0};
      map['end'] = {'x': 0.5, 'y': 1.0};
    }
  } else if (typeName.contains('RadialGradient')) {
    map['type'] = 'radial';
    try {
      final center = gradient.center as Alignment;
      map['center'] = {'x': (center.x + 1) / 2, 'y': (center.y + 1) / 2};
      map['radius'] = gradient.radius as double;
    } catch (_) {
      map['center'] = {'x': 0.5, 'y': 0.5};
      map['radius'] = 0.5;
    }
  } else if (typeName.contains('SweepGradient')) {
    map['type'] = 'sweep';
    try {
      final center = gradient.center as Alignment;
      map['center'] = {'x': (center.x + 1) / 2, 'y': (center.y + 1) / 2};
      map['startAngle'] = gradient.startAngle as double;
      map['endAngle'] = gradient.endAngle as double;
    } catch (_) {
      map['center'] = {'x': 0.5, 'y': 0.5};
    }
  }
  return map;
}

/// 노드 트리에 실질적 콘텐츠(Text, Image, visual 있는 Frame)가 있는지
bool _hasContentRecursive(Map<String, dynamic> node) {
  final type = node['type'];
  if (type == 'Text' || type == 'Image') return true;
  final vis = node['visual'] as Map<String, dynamic>? ?? {};
  if (vis['content'] != null ||
      vis['backgroundColor'] != null ||
      vis['gradient'] != null ||
      vis['border'] != null ||
      vis['imagePath'] != null)
    return true;
  final children = node['children'] as List?;
  if (children == null) return false;
  for (final c in children) {
    if (c is Map<String, dynamic> && _hasContentRecursive(c)) return true;
  }
  return false;
}

/// visual 속성이 있는지 (배경, 테두리, 그림자 등)
bool _hasVisualProps(Map<String, dynamic> visual) {
  return visual['backgroundColor'] != null ||
      (visual['border'] != null) ||
      (visual['shadow'] != null) ||
      visual['borderRadius'] != null ||
      visual['isIconBox'] == true ||
      visual['isSvgBox'] == true ||
      visual['isTextField'] == true ||
      visual['isDivider'] == true ||
      visual['backgroundBlur'] != null;
}

/// =======================================================
/// 3. Render 트리 크롤러 (Schema v2)
/// =======================================================

/// SliverPadding에서 패딩을 추출하여 containerLayout에 저장
void _extractSliverPadding(RenderObject sliver, Map<String, dynamic> cl) {
  if (sliver is RenderSliverPadding) {
    final EdgeInsets? resolved = sliver.resolvedPadding;
    if (resolved != null && !cl.containsKey('padding')) {
      cl['padding'] = {
        'top': resolved.top,
        'right': resolved.right,
        'bottom': resolved.bottom,
        'left': resolved.left,
      };
    }
  }
  sliver.visitChildren((child) {
    if (child is! RenderBox) {
      _extractSliverPadding(child, cl);
    }
  });
}

List<Map<String, dynamic>> _crawlThroughSliver(RenderObject sliver) {
  // SliverGrid → ROW 단위로 그룹핑하여 COLUMN > ROW * n 구조 생성
  if (sliver is RenderSliverGrid) {
    final List<Map<String, dynamic>> gridChildren = [];
    sliver.visitChildren((child) {
      if (child is RenderBox) {
        final res = _crawl(child);
        if (res != null) gridChildren.add(res);
      }
    });
    if (gridChildren.isEmpty) return [];

    // crossAxisCount + spacing 추출 (gridDelegate에서)
    int crossAxisCount = 2; // 기본값
    double crossAxisSpacing = 0.0;
    double mainAxisSpacing = 0.0;
    try {
      final delegate = (sliver as dynamic).gridDelegate;
      if (delegate is SliverGridDelegateWithFixedCrossAxisCount) {
        crossAxisCount = delegate.crossAxisCount;
        crossAxisSpacing = delegate.crossAxisSpacing;
        mainAxisSpacing = delegate.mainAxisSpacing;
      }
    } catch (_) {}

    // 자식을 ROW 단위로 그룹핑
    final List<Map<String, dynamic>> rows = [];
    for (int i = 0; i < gridChildren.length; i += crossAxisCount) {
      final end = (i + crossAxisCount).clamp(0, gridChildren.length);
      final rowChildren = gridChildren.sublist(i, end);
      // 각 자식에 flexGrow 설정
      for (final rc in rowChildren) {
        final cl = rc['childLayout'] as Map<String, dynamic>? ?? {};
        cl['flexGrow'] = 1;
        cl['sizingH'] = 'FILL';
        cl['sizingV'] = 'HUG';
        rc['childLayout'] = cl;
      }
      // ROW 래퍼 생성
      final firstRect = rowChildren.first['rect'] as Map<String, dynamic>;
      rows.add({
        'type': 'Frame',
        'layoutMode': 'ROW',
        'rect': {
          'x': firstRect['x'],
          'y': firstRect['y'],
          'w': sliver.constraints.crossAxisExtent,
          'h': (firstRect['h'] as num).toDouble(),
        },
        'visual': <String, dynamic>{},
        'containerLayout': {
          'mainAxisAlignment': 'start',
          'crossAxisAlignment': 'start',
          'mainAxisSize': 'max',
          'itemSpacing': crossAxisSpacing,
        },
        'children': rowChildren,
      });
    }
    // 행 간격은 부모 COLUMN의 itemSpacing으로 처리됨 (mainAxisSpacing)
    // rows에 mainAxisSpacing 정보를 첨부하여 상위에서 사용
    if (rows.isNotEmpty && mainAxisSpacing > 0) {
      // _crawlThroughSliver 결과는 바로 COLUMN children이 되므로
      // 상위 _crawl에서 itemSpacing 계산 시 gap이 반영됨
    }
    return rows;
  }

  final List<Map<String, dynamic>> results = [];
  sliver.visitChildren((child) {
    if (child is RenderBox) {
      final res = _crawl(child);
      if (res != null) results.add(res);
    } else {
      results.addAll(_crawlThroughSliver(child));
    }
  });
  return results;
}

/// 메인 크롤 함수: RenderObject → 새 스키마 노드
Map<String, dynamic>? _crawl(RenderObject? node) {
  if (node == null) return null;

  // Sliver 노드: 통과하여 내부 RenderBox 수집
  if (node is! RenderBox) {
    final sliverChildren = _crawlThroughSliver(node);
    if (sliverChildren.isEmpty) return null;
    if (sliverChildren.length == 1) return sliverChildren.first;
    return {
      'type': 'Frame',
      'layoutMode': 'COLUMN',
      'rect': sliverChildren.first['rect'],
      'visual': <String, dynamic>{},
      'containerLayout': <String, dynamic>{},
      'children': sliverChildren,
    };
  }

  if (!node.hasSize) return null;
  if (node.size.width == 0 && node.size.height == 0) return null;
  if (node is RenderOffstage && node.offstage) return null;

  // Checkbox / Switch 등: 이미지로 캡처된 경우
  // PNG는 사방 8px 여유 포함, wrapper Frame은 실제 크기 + center/center 정렬
  if (_customPaintCaptures.contains(node)) {
    final b64 = _imageDataByNode[node];
    if (b64 != null) {
      Offset cpOffset;
      try {
        cpOffset = node.localToGlobal(Offset.zero);
      } catch (_) {
        try {
          cpOffset = (node.parentData as BoxParentData).offset;
        } catch (_) {
          cpOffset = Offset.zero;
        }
      }
      const double pad = 4.0;
      return {
        'type': 'Frame',
        'layoutMode': 'NONE',
        'clipsContent': false,
        'rect': {
          'x': cpOffset.dx,
          'y': cpOffset.dy,
          'w': node.size.width,
          'h': node.size.height,
        },
        'visual': <String, dynamic>{},
        'containerLayout': {
          'mainAxisAlignment': 'center',
          'crossAxisAlignment': 'center',
        },
        'children': <Map<String, dynamic>>[
          {
            'type': 'Image',
            'layoutMode': 'NONE',
            'rect': {
              'x': -pad,
              'y': -pad,
              'w': node.size.width + pad * 2,
              'h': node.size.height + pad * 2,
            },
            'visual': {'imageBase64': b64, 'imageFit': 'fill'},
            'children': <Map<String, dynamic>>[],
          },
        ],
      };
    }
  }

  Offset offset;
  try {
    offset = node.localToGlobal(Offset.zero);
  } catch (_) {
    return null;
  }

  // 기본값
  String type = 'Frame';
  String layoutMode = 'NONE';
  final Map<String, dynamic> visual = {};
  final Map<String, dynamic> containerLayout = {};
  bool hasVisual = false;
  bool isLayoutNode = false;
  bool isSizedBox = false;
  bool isCustomMultiChild = false;

  final String runtimeTypeStr = node.runtimeType.toString();
  final bool isSvgBoxTarget = _svgBoxTargets.contains(node);

  String? backgroundImagePath;
  String? backgroundImageFit;

  // ---------------------------------------------------
  // [0] SvgPicture placeholder
  // ---------------------------------------------------
  if (isSvgBoxTarget) {
    hasVisual = true;
    visual['backgroundColor'] = '#ffdddddd';
    visual['isSvgBox'] = true;
  }
  // ---------------------------------------------------
  // [1] Text / Icon
  // ---------------------------------------------------
  else if (node is RenderParagraph) {
    TextStyle? style;
    InlineSpan inlineSpan = node.text;
    if (inlineSpan is TextSpan) {
      style = inlineSpan.style;
    }
    final String? fontFamily = style?.fontFamily;

    if (fontFamily != null && fontFamily.contains('MaterialIcons')) {
      type = 'Frame';
      hasVisual = true;
      final Color color = style?.color ?? const Color(0xFF000000);
      visual['backgroundColor'] = _colorToHex(color);
      visual['isIconBox'] = true;
      // pre-captured 아이콘 이미지 lookup
      final b64 = _imageDataByNode[node];
      if (b64 != null) {
        visual['iconImageBase64'] = b64;
      }
    } else {
      type = 'Text';
      hasVisual = true;
      try {
        visual['content'] = node.text.toPlainText();
        visual['textAlign'] = node.textAlign.toString().split('.').last;

        // RichText children: 개별 TextSpan 스타일을 textSpans 배열로 내보내기
        if (inlineSpan is TextSpan) {
          final spanChildren = inlineSpan.children;
          if (spanChildren != null && spanChildren.isNotEmpty) {
            final spans = <Map<String, dynamic>>[];
            int charOffset = 0;
            for (final child in spanChildren) {
              if (child is TextSpan) {
                final spanText = child.text ?? '';
                if (spanText.isNotEmpty) {
                  final spanMap = <String, dynamic>{
                    'start': charOffset,
                    'end': charOffset + spanText.length,
                  };
                  final s = child.style;
                  if (s != null) {
                    if (s.fontSize != null) spanMap['fontSize'] = s.fontSize;
                    if (s.fontWeight != null) spanMap['fontWeight'] = s.fontWeight.toString();
                    if (s.color != null) spanMap['color'] = _colorToHex(s.color);
                    if (s.fontFamily != null) spanMap['fontFamily'] = s.fontFamily;
                    if (s.letterSpacing != null) spanMap['letterSpacing'] = s.letterSpacing;
                    if (s.height != null) spanMap['lineHeightMultiplier'] = s.height;
                  }
                  spans.add(spanMap);
                  charOffset += spanText.length;
                }
              }
            }
            if (spans.isNotEmpty) {
              visual['textSpans'] = spans;
            }
            // 최상위 style이 없으면 첫 번째 자식 style을 fallback
            if (style == null || (style.fontSize == null && style.fontWeight == null)) {
              final first = spanChildren.first;
              if (first is TextSpan && first.style != null) {
                style = first.style;
              }
            }
          }
        }

        if (style != null) {
          visual['fontFamily'] = style.fontFamily;
          visual['fontSize'] = style.fontSize;
          visual['fontWeight'] = style.fontWeight.toString();
          visual['color'] = _colorToHex(style.color);
          visual['letterSpacing'] = style.letterSpacing;
          if (style.height != null) {
            visual['lineHeightMultiplier'] = style.height;
          }
        }
      } catch (_) {}

      // ShaderMask gradient → 텍스트에 gradient fill 적용
      final smGradient = _shaderMaskGradients[node];
      if (smGradient != null) {
        visual['gradient'] = smGradient;
      }
    }
  }
  // ---------------------------------------------------
  // [1.5] Editable Text (TextField 입력 텍스트)
  // ---------------------------------------------------
  else if (node is RenderEditable) {
    type = 'Text';
    hasVisual = true;
    try {
      final text = node.text;
      final plainText = text?.toPlainText() ?? '';
      if (plainText.isNotEmpty) {
        visual['content'] = plainText;
        visual['textAlign'] = node.textAlign.toString().split('.').last;
        TextStyle? style;
        if (text is TextSpan) {
          style = text.style;
        }
        if (style != null) {
          visual['fontFamily'] = style.fontFamily;
          visual['fontSize'] = style.fontSize;
          visual['fontWeight'] = style.fontWeight.toString();
          visual['color'] = _colorToHex(style.color);
          visual['letterSpacing'] = style.letterSpacing;
          if (style.height != null) {
            visual['lineHeightMultiplier'] = style.height;
          }
        }
      }
    } catch (_) {}
  }
  // ---------------------------------------------------
  // [2] Image
  // ---------------------------------------------------
  else if (node is RenderImage) {
    type = 'Image';
    hasVisual = true;
    try {
      visual['imagePath'] = node.debugImageLabel;
      visual['imageFit'] = 'cover';
      // pre-captured 이미지 데이터 lookup
      final b64 = _imageDataByNode[node];
      if (b64 != null) {
        visual['imageBase64'] = b64;
      }
    } catch (_) {}
  }
  // ---------------------------------------------------
  // [2.5] Padding (RenderPadding) — 자식에 병합
  // ---------------------------------------------------
  else if (node is RenderPadding) {
    final EdgeInsetsGeometry resolvedPadding = node.padding;
    EdgeInsets insets;
    if (resolvedPadding is EdgeInsets) {
      insets = resolvedPadding;
    } else {
      insets = resolvedPadding.resolve(TextDirection.ltr);
    }

    final paddingMap = {
      'top': insets.top,
      'right': insets.right,
      'bottom': insets.bottom,
      'left': insets.left,
    };

    RenderBox? singleChild;
    int childCount = 0;
    node.visitChildren((child) {
      childCount++;
      if (child is RenderBox) singleChild = child;
    });

    // Padding + RenderFlex → padding을 Flex containerLayout에 병합
    if (childCount == 1 && singleChild is RenderFlex) {
      final flexResult = _crawl(singleChild);
      if (flexResult != null) {
        final cl = flexResult['containerLayout'] as Map<String, dynamic>? ?? {};
        cl['padding'] = paddingMap;
        flexResult['containerLayout'] = cl;
        flexResult['rect'] = {
          'x': offset.dx,
          'y': offset.dy,
          'w': node.size.width,
          'h': node.size.height,
        };
        return flexResult;
      }
    }

    // Padding + RenderStack → padding을 Stack containerLayout에 병합
    if (childCount == 1 && singleChild is RenderStack) {
      final stackResult = _crawl(singleChild);
      if (stackResult != null) {
        final cl =
            stackResult['containerLayout'] as Map<String, dynamic>? ?? {};
        cl['padding'] = paddingMap;
        stackResult['containerLayout'] = cl;
        stackResult['rect'] = {
          'x': offset.dx,
          'y': offset.dy,
          'w': node.size.width,
          'h': node.size.height,
        };
        return stackResult;
      }
    }

    // 기타: Frame(COLUMN) + padding
    // RenderPadding은 tight constraints를 자식에게 전달 → stretch가 올바른 매핑
    type = 'Frame';
    layoutMode = 'COLUMN';
    isLayoutNode = true;
    containerLayout['padding'] = paddingMap;
    containerLayout['mainAxisAlignment'] = 'start';
    containerLayout['crossAxisAlignment'] = 'stretch';
    containerLayout['mainAxisSize'] = 'min';
    containerLayout['itemSpacing'] = 0.0;
  }
  // ---------------------------------------------------
  // [3] RenderStack (신규)
  // ---------------------------------------------------
  else if (node is RenderStack) {
    type = 'Frame';
    layoutMode = 'STACK';
    isLayoutNode = true;
  }
  // ---------------------------------------------------
  // [3.5] RenderPositionedBox (Align / Center / Container.alignment)
  // ---------------------------------------------------
  else if (node is RenderPositionedBox) {
    type = 'Frame';
    isLayoutNode = true;
    layoutMode = 'COLUMN';

    final alignment = node.alignment;
    Alignment resolved;
    if (alignment is Alignment) {
      resolved = alignment;
    } else {
      resolved = alignment.resolve(TextDirection.ltr);
    }

    // alignment.y → mainAxisAlignment (COLUMN = vertical)
    String mainAlign;
    if (resolved.y <= -0.5) {
      mainAlign = 'start';
    } else if (resolved.y >= 0.5) {
      mainAlign = 'end';
    } else {
      mainAlign = 'center';
    }

    // alignment.x → crossAxisAlignment (COLUMN = horizontal)
    String crossAlign;
    if (resolved.x <= -0.5) {
      crossAlign = 'start';
    } else if (resolved.x >= 0.5) {
      crossAlign = 'end';
    } else {
      crossAlign = 'center';
    }

    containerLayout['mainAxisAlignment'] = mainAlign;
    containerLayout['crossAxisAlignment'] = crossAlign;
    containerLayout['mainAxisSize'] = 'max';
  }
  // ---------------------------------------------------
  // [4] RenderConstrainedBox (SizedBox)
  // ---------------------------------------------------
  else if (node is RenderConstrainedBox) {
    isSizedBox = true;
    // 자식 확인
    RenderBox? singleChild;
    int childCount = 0;
    node.visitChildren((child) {
      childCount++;
      if (child is RenderBox) singleChild = child;
    });

    if (childCount == 1 && singleChild != null) {
      // 자식 있으면 투과 — 크기 정보만 childLayout에서 처리
      final childResult = _crawl(singleChild);
      if (childResult != null) {
        // rect를 SizedBox 기준으로 업데이트
        childResult['rect'] = {
          'x': offset.dx,
          'y': offset.dy,
          'w': node.size.width,
          'h': node.size.height,
        };
        // Tight constraints → fixedSize / fixedWidth / fixedHeight 마킹
        // 렌더 크기 ≈ 제약 크기일 때만 (Expanded 안 SizedBox 제외)
        final ac = node.additionalConstraints;
        final cl = childResult['childLayout'] as Map<String, dynamic>? ?? {};
        bool marked = false;
        if (ac.hasTightWidth && ac.maxWidth.isFinite) {
          if ((node.size.width - ac.maxWidth).abs() < 1.0) {
            cl['fixedWidth'] = true;
            marked = true;
          }
        }
        if (ac.hasTightHeight && ac.maxHeight.isFinite) {
          if ((node.size.height - ac.maxHeight).abs() < 1.0) {
            cl['fixedHeight'] = true;
            marked = true;
          }
        }
        if (cl['fixedWidth'] == true && cl['fixedHeight'] == true) {
          cl['fixedSize'] = true;
        }
        if (marked) {
          childResult['childLayout'] = cl;
        }
        return childResult;
      }
    }

    // 자식 없으면 Spacer 역할 (빈 Frame)
    type = 'Frame';
    layoutMode = 'NONE';
  }
  // ---------------------------------------------------
  // [5] Flex (Row / Column)
  // ---------------------------------------------------
  else if (node is RenderFlex) {
    type = 'Frame';
    isLayoutNode = true;
    layoutMode = node.direction == Axis.horizontal ? 'ROW' : 'COLUMN';

    final mainAlign = node.mainAxisAlignment.toString().split('.').last;
    final crossAlign = node.crossAxisAlignment.toString().split('.').last;
    final mainSize = node.mainAxisSize == MainAxisSize.min ? 'min' : 'max';

    containerLayout['mainAxisAlignment'] = mainAlign;
    containerLayout['crossAxisAlignment'] = crossAlign;
    containerLayout['mainAxisSize'] = mainSize;
  }
  // ---------------------------------------------------
  // [5.5] RenderWrap
  // ---------------------------------------------------
  else if (node is RenderWrap) {
    type = 'Frame';
    isLayoutNode = true;
    layoutMode = 'WRAP';
    containerLayout['itemSpacing'] = node.spacing;
    containerLayout['runSpacing'] = node.runSpacing;
    containerLayout['mainAxisAlignment'] = node.alignment
        .toString()
        .split('.')
        .last;
    containerLayout['crossAxisAlignment'] = node.crossAxisAlignment
        .toString()
        .split('.')
        .last;
  }
  // ---------------------------------------------------
  // [6] DecoratedBox
  // ---------------------------------------------------
  else if (node is RenderDecoratedBox) {
    type = 'Frame';
    try {
      final decoration = node.decoration;
      if (decoration is BoxDecoration) {
        if (decoration.color != null) {
          visual['backgroundColor'] = _colorToHex(decoration.color);
          hasVisual = true;
        }
        if (decoration.gradient != null) {
          final grad = _extractGradient(decoration.gradient);
          if (grad != null) {
            visual['gradient'] = grad;
            hasVisual = true;
          }
        }
        if (decoration.image != null) {
          final DecorationImage decorationImage = decoration.image!;
          final ImageProvider provider = decorationImage.image;
          if (provider is AssetImage) {
            backgroundImagePath = provider.assetName;
            backgroundImageFit = decorationImage.fit?.toString();
            hasVisual = true;
          }
        }
        if (decoration.border != null) {
          final border = decoration.border;
          if (border is Border) {
            final top = border.top,
                right = border.right,
                bottom = border.bottom,
                left = border.left;
            final sides = [top, right, bottom, left];
            BorderSide? bestSide;
            for (final s in sides) {
              if (bestSide == null || s.width > bestSide.width) bestSide = s;
            }
            if (bestSide != null && bestSide.width > 0) {
              final borderMap = <String, dynamic>{
                'color': _colorToHex(bestSide.color),
                'width': bestSide.width,
              };
              final uniform = sides.every(
                (s) => s.width == top.width && s.color == top.color,
              );
              if (!uniform) {
                borderMap['topWidth'] = top.width;
                borderMap['rightWidth'] = right.width;
                borderMap['bottomWidth'] = bottom.width;
                borderMap['leftWidth'] = left.width;
              }
              visual['border'] = borderMap;
              hasVisual = true;
            }
          } else {
            visual['border'] = {'color': '#ff000000', 'width': 1.0};
            hasVisual = true;
          }
        }
        // BoxShape.circle → borderRadius = shortestSide / 2
        if (decoration.shape == BoxShape.circle) {
          visual['borderRadius'] = node.size.shortestSide / 2;
        } else {
          final br = _parseBorderRadius(decoration.borderRadius);
          if (br != null) visual['borderRadius'] = br;
        }
        if (decoration.boxShadow != null && decoration.boxShadow!.isNotEmpty) {
          final s = decoration.boxShadow!.first;
          visual['shadow'] = {
            'color': _colorToHex(s.color),
            'offsetX': s.offset.dx,
            'offsetY': s.offset.dy,
            'blurRadius': s.blurRadius,
            'spreadRadius': s.spreadRadius,
          };
          hasVisual = true;
        }
      }
      // ShapeDecoration (Material 버튼: OutlinedButton, ElevatedButton 등)
      else if (decoration is ShapeDecoration) {
        if (decoration.color != null) {
          visual['backgroundColor'] = _colorToHex(decoration.color);
          hasVisual = true;
        }
        final shape = decoration.shape;
        if (shape is RoundedRectangleBorder) {
          final side = shape.side;
          if (side.width > 0 && side.style == BorderStyle.solid) {
            visual['border'] = {
              'color': _colorToHex(side.color),
              'width': side.width,
            };
            hasVisual = true;
          }
          final br = _parseBorderRadius(shape.borderRadius);
          if (br != null) visual['borderRadius'] = br;
        } else if (shape is StadiumBorder) {
          final side = shape.side;
          if (side.width > 0 && side.style == BorderStyle.solid) {
            visual['border'] = {
              'color': _colorToHex(side.color),
              'width': side.width,
            };
            hasVisual = true;
          }
          // StadiumBorder → borderRadius = height / 2
          visual['borderRadius'] = node.size.height / 2;
        } else if (shape is CircleBorder) {
          final side = shape.side;
          if (side.width > 0 && side.style == BorderStyle.solid) {
            visual['border'] = {
              'color': _colorToHex(side.color),
              'width': side.width,
            };
            hasVisual = true;
          }
          visual['borderRadius'] = node.size.shortestSide / 2;
        }
        if (decoration.shadows != null && decoration.shadows!.isNotEmpty) {
          final s = decoration.shadows!.first;
          visual['shadow'] = {
            'color': _colorToHex(s.color),
            'offsetX': s.offset.dx,
            'offsetY': s.offset.dy,
            'blurRadius': s.blurRadius,
            'spreadRadius': s.spreadRadius,
          };
          hasVisual = true;
        }
      }
    } catch (_) {}
  }
  // ---------------------------------------------------
  // [7] PhysicalModel
  // ---------------------------------------------------
  else if (node is RenderPhysicalModel) {
    type = 'Frame';
    hasVisual = true;
    visual['backgroundColor'] = _colorToHex(node.color);
    if (node.elevation > 0) {
      visual['shadow'] = {'elevation': node.elevation};
    }
    try {
      dynamic d = node;
      if (d.borderRadius != null) {
        final br = _parseBorderRadius(d.borderRadius);
        if (br != null) visual['borderRadius'] = br;
      }
    } catch (_) {}
  }
  // ---------------------------------------------------
  // [8] PhysicalShape
  // ---------------------------------------------------
  else if (node is RenderPhysicalShape) {
    type = 'Frame';
    hasVisual = true;
    visual['backgroundColor'] = _colorToHex(node.color);
    if (node.elevation > 0) {
      visual['shadow'] = {'elevation': node.elevation};
    }
    try {
      final diagnostics = node.toDiagnosticsNode();
      final properties = diagnostics.getProperties();
      final clipperProp = properties.firstWhere(
        (p) => p.name == 'clipper',
        orElse: () => DiagnosticsProperty('dummy', null),
      );
      if (clipperProp.value != null) {
        dynamic clipper = clipperProp.value;
        dynamic shape = clipper.shape;
        final shapeStr = shape.toString();
        final reg = RegExp(r'circular\(([\d\.]+)\)');
        final m = reg.firstMatch(shapeStr);
        if (m != null) {
          visual['borderRadius'] = double.tryParse(m.group(1)!) ?? 0.0;
        }
        // shape.side → border (OutlinedButton 등 Material 버튼의 보더)
        try {
          final side = shape.side;
          if (side != null &&
              side.width > 0 &&
              side.style == BorderStyle.solid) {
            visual['border'] = {
              'color': _colorToHex(side.color),
              'width': side.width,
            };
          }
        } catch (_) {}
      }
    } catch (_) {}
  }
  // ---------------------------------------------------
  // [8.5] RenderClipRRect
  // ---------------------------------------------------
  else if (node is RenderClipRRect) {
    final br = _parseBorderRadius(node.borderRadius);
    RenderBox? singleChild;
    int childCount = 0;
    node.visitChildren((child) {
      childCount++;
      if (child is RenderBox) singleChild = child;
    });
    if (childCount == 1 && singleChild != null) {
      final childResult = _crawl(singleChild);
      if (childResult != null) {
        if (br != null && br > 0) {
          final childVisual =
              childResult['visual'] as Map<String, dynamic>? ?? {};
          if (!childVisual.containsKey('borderRadius')) {
            childVisual['borderRadius'] = br;
            childResult['visual'] = childVisual;
          }
        }
        childResult['rect'] = {
          'x': offset.dx,
          'y': offset.dy,
          'w': node.size.width,
          'h': node.size.height,
        };
        return childResult;
      }
    }
    type = 'Frame';
    layoutMode = 'NONE';
    if (br != null && br > 0) visual['borderRadius'] = br;
  }
  // ---------------------------------------------------
  // [8.55] RenderBackdropFilter → backgroundBlur
  // ---------------------------------------------------
  else if (runtimeTypeStr.contains('RenderBackdropFilter')) {
    type = 'Frame';
    layoutMode = 'NONE';
    // blur sigma를 visual에 추가 (element tree 매핑 우선, 실패 시 직접 추출)
    double? blurSigma = _blurInfoByRenderObject[node];
    if (blurSigma == null || blurSigma <= 0) {
      // fallback: RenderBackdropFilter.filter에서 직접 추출
      try {
        final filterObj = (node as dynamic).filter;
        final filterStr = filterObj.toString();
        // "sigmaX: 10.0" 형식
        var m = RegExp(r'sigmaX:\s*([\d.]+)').firstMatch(filterStr);
        // "blur(10.0, 10.0, ...)" 형식 (parameter name 없는 경우)
        m ??= RegExp(r'blur\(([\d.]+)').firstMatch(filterStr);
        if (m != null) {
          blurSigma = double.tryParse(m.group(1)!) ?? 0;
        }
      } catch (e) {
        debugPrint('[BackdropFilter] filter extraction failed: $e');
      }
    }
    if (blurSigma != null && blurSigma > 0) {
      visual['backgroundBlur'] = blurSigma;
      hasVisual = true;
    }
  }
  // ---------------------------------------------------
  // [8.57] RenderTransform → rotation 추출
  // ---------------------------------------------------
  else if (runtimeTypeStr.contains('RenderTransform')) {
    type = 'Frame';
    layoutMode = 'NONE';
    // 방법 1 (확실): widget tree에서 미리 캡처한 rotation 사용
    final precomputed = _rotationByRenderObject[node];
    if (precomputed != null && precomputed.abs() > 0.001) {
      visual['rotation'] = precomputed;
    } else {
      // 방법 2 (fallback): RenderObject에서 직접 추출 시도
      try {
        Matrix4? transform;
        try {
          transform = (node as dynamic).transform as Matrix4?;
        } catch (_) {}
        transform ??= (() {
          try {
            final parent = node.parent;
            if (parent is RenderObject) return node.getTransformTo(parent);
          } catch (_) {}
          return null;
        })();
        if (transform != null) {
          final sinVal = transform.entry(1, 0);
          final cosVal = transform.entry(0, 0);
          final radians = math.atan2(sinVal, cosVal);
          if (radians.abs() > 0.001) {
            visual['rotation'] = radians * 180.0 / math.pi;
          }
        }
      } catch (e) {
        debugPrint('[RenderTransform] rotation extraction failed: $e');
      }
    }
    // 단일 자식이면 패스스루
    RenderBox? singleChild;
    int childCount = 0;
    node.visitChildren((child) {
      childCount++;
      if (child is RenderBox) singleChild = child;
    });
    if (childCount == 1 && singleChild != null) {
      final childResult = _crawl(singleChild);
      if (childResult != null) {
        // rotation을 자식에 전파
        if (visual.containsKey('rotation')) {
          final childVisual =
              childResult['visual'] as Map<String, dynamic>? ?? {};
          childVisual['rotation'] = visual['rotation'];
          childResult['visual'] = childVisual;
        }
        childResult['rect'] = {
          'x': offset.dx,
          'y': offset.dy,
          'w': node.size.width,
          'h': node.size.height,
        };
        return childResult;
      }
    }
  }
  // ---------------------------------------------------
  // [8.6] RenderClipPath
  // ---------------------------------------------------
  else if (runtimeTypeStr.contains('RenderClipPath')) {
    RenderBox? singleChild;
    int childCount = 0;
    node.visitChildren((child) {
      childCount++;
      if (child is RenderBox) singleChild = child;
    });
    if (childCount == 1 && singleChild != null) {
      final childResult = _crawl(singleChild);
      if (childResult != null) {
        childResult['rect'] = {
          'x': offset.dx,
          'y': offset.dy,
          'w': node.size.width,
          'h': node.size.height,
        };
        return childResult;
      }
    }
    type = 'Frame';
    layoutMode = 'NONE';
  }
  // ---------------------------------------------------
  // [9] Picture / CustomPaint
  // ---------------------------------------------------
  else if (runtimeTypeStr.contains('Picture') ||
      runtimeTypeStr.contains('CustomPaint')) {
    type = 'Frame';
    hasVisual = false;
  }
  // ---------------------------------------------------
  // [9.5] CustomMultiChildLayout (NavigationToolbar, Scaffold 등)
  // ---------------------------------------------------
  else if (runtimeTypeStr.contains('CustomMultiChildLayoutBox')) {
    type = 'Frame';
    isLayoutNode = true;
    isCustomMultiChild = true;

    // 자식 좌표를 보고 방향 추론
    double minX = double.infinity, maxX = -double.infinity;
    double minY = double.infinity, maxY = -double.infinity;
    int peekCount = 0;
    node.visitChildren((child) {
      if (child is RenderBox && child.hasSize) {
        try {
          final o = child.localToGlobal(Offset.zero);
          if (o.dx < minX) minX = o.dx;
          if (o.dx > maxX) maxX = o.dx;
          if (o.dy < minY) minY = o.dy;
          if (o.dy > maxY) maxY = o.dy;
          peekCount++;
        } catch (_) {}
      }
    });

    if (peekCount >= 2) {
      final xRange = maxX - minX;
      final yRange = maxY - minY;
      layoutMode = xRange > yRange ? 'ROW' : 'COLUMN';
    } else {
      layoutMode = 'ROW';
    }

    if (layoutMode == 'ROW') {
      containerLayout['mainAxisAlignment'] = 'spaceBetween';
      containerLayout['crossAxisAlignment'] = 'center';
      containerLayout['mainAxisSize'] = 'max';
    } else {
      containerLayout['mainAxisAlignment'] = 'start';
      containerLayout['crossAxisAlignment'] = 'stretch';
      containerLayout['mainAxisSize'] = 'max';
    }
  }

  // ---------------------------------------------------
  // [10] DesignInfo overlay (TextField, Divider, Container)
  // ---------------------------------------------------
  final designInfo = _designInfoByRenderObject[node];
  if (designInfo != null) {
    if (designInfo.backgroundColor != null) {
      visual['backgroundColor'] = _colorToHex(designInfo.backgroundColor);
      hasVisual = true;
    }
    if (designInfo.borderColor != null) {
      final borderMap = <String, dynamic>{
        'color': _colorToHex(designInfo.borderColor),
        'width': designInfo.borderWidth ?? 1.0,
      };
      if (designInfo.borderTopWidth != null) {
        borderMap['topWidth'] = designInfo.borderTopWidth;
        borderMap['rightWidth'] = designInfo.borderRightWidth;
        borderMap['bottomWidth'] = designInfo.borderBottomWidth;
        borderMap['leftWidth'] = designInfo.borderLeftWidth;
      }
      visual['border'] = borderMap;
      hasVisual = true;
    }
    if (designInfo.borderRadius != null) {
      visual['borderRadius'] = designInfo.borderRadius;
    }
    if (designInfo.elevation != null && designInfo.elevation! > 0) {
      visual['shadow'] = {'elevation': designInfo.elevation};
    }
    if (designInfo.isTextField) visual['isTextField'] = true;
    if (designInfo.isDivider) visual['isDivider'] = true;
  }

  // ---------------------------------------------------
  // [10.5] TextField 구조 재편 플래그
  // ---------------------------------------------------
  final bool isTextFieldNode = visual['isTextField'] == true;

  // ---------------------------------------------------
  // [11] 자식 순회
  // ---------------------------------------------------
  final List<Map<String, dynamic>> children = [];
  final bool _skipChildren = (type == 'Text');
  final bool isFlex = node is RenderFlex;
  final bool isStack = node is RenderStack;
  final bool isWrap = node is RenderWrap;
  final List<double> _gaps = [];
  final List<double> _childMainAxisPositions = [];
  double? _lastChildEnd; // gap 계산용: 이전 non-null 자식의 끝 좌표

  try {
    if (!_skipChildren)
      node.visitChildren((child) {
        if (child is RenderBox) {
          final c = _crawl(child);
          if (c != null) {
            // Flex 자식: childLayout 설정
            if (isFlex) {
              final flexNode = node as RenderFlex;
              final isHorizontal = flexNode.direction == Axis.horizontal;
              final childLayout =
                  c['childLayout'] as Map<String, dynamic>? ?? {};

              final parentData = child.parentData;
              if (parentData is FlexParentData) {
                final flex = parentData.flex ?? 0;
                final isTight = parentData.fit == FlexFit.tight;

                if (flex > 0 && isTight) {
                  // Expanded
                  childLayout['flexGrow'] = flex;
                  if (isHorizontal) {
                    childLayout['sizingH'] = 'FILL';
                    childLayout['sizingV'] = 'HUG';
                  } else {
                    childLayout['sizingH'] = 'HUG';
                    childLayout['sizingV'] = 'FILL';
                  }
                } else if (flex > 0) {
                  // Flexible (loose)
                  childLayout['flexGrow'] = flex;
                  childLayout['sizingH'] = 'HUG';
                  childLayout['sizingV'] = 'HUG';
                } else {
                  // 일반 자식
                  childLayout['flexGrow'] = 0;
                  childLayout['sizingH'] = 'HUG';
                  childLayout['sizingV'] = 'HUG';
                }
              } else {
                childLayout['flexGrow'] = 0;
                childLayout['sizingH'] = 'HUG';
                childLayout['sizingV'] = 'HUG';
              }

              // crossAxisAlignment == stretch → cross축 FILL
              if (flexNode.crossAxisAlignment == CrossAxisAlignment.stretch) {
                if (isHorizontal) {
                  childLayout['sizingV'] = 'FILL';
                  childLayout['alignSelf'] = 'STRETCH';
                } else {
                  childLayout['sizingH'] = 'FILL';
                  childLayout['alignSelf'] = 'STRETCH';
                }
              }

              c['childLayout'] = childLayout;

              // itemSpacing 계산용 좌표 수집 + gap 즉시 계산
              try {
                final childOffset = child.localToGlobal(Offset.zero);
                final pos = isHorizontal ? childOffset.dx : childOffset.dy;
                final size = isHorizontal ? child.size.width : child.size.height;
                _childMainAxisPositions.add(pos);
                if (_lastChildEnd != null) {
                  final gap = pos - _lastChildEnd!;
                  if (gap > 0) _gaps.add(gap.roundToDouble());
                }
                _lastChildEnd = pos + size;
              } catch (_) {}
            }

            // Stack 자식: positioned 정보 추출
            if (isStack) {
              final childLayout =
                  c['childLayout'] as Map<String, dynamic>? ?? {};
              final parentData = child.parentData;
              if (parentData is StackParentData) {
                final pos = <String, dynamic>{};
                if (parentData.top != null) pos['top'] = parentData.top;
                if (parentData.left != null) pos['left'] = parentData.left;
                if (parentData.right != null) pos['right'] = parentData.right;
                if (parentData.bottom != null)
                  pos['bottom'] = parentData.bottom;
                if (pos.isNotEmpty) {
                  childLayout['positioned'] = pos;
                }
              }
              childLayout['sizingH'] = 'FIXED';
              childLayout['sizingV'] = 'FIXED';
              c['childLayout'] = childLayout;
            }

            // Wrap 자식: HUG 사이징 (자연 크기 유지)
            if (isWrap) {
              final childLayout =
                  c['childLayout'] as Map<String, dynamic>? ?? {};
              childLayout['sizingH'] = 'HUG';
              childLayout['sizingV'] = 'HUG';
              c['childLayout'] = childLayout;
            }

            children.add(c);
          }
        } else {
          // SliverPadding 감지 → padding + layout 설정
          _extractSliverPadding(child, containerLayout);
          if (containerLayout.containsKey('padding') && layoutMode == 'NONE') {
            layoutMode = 'COLUMN';
            isLayoutNode = true;
            containerLayout['crossAxisAlignment'] = 'stretch';
            containerLayout['mainAxisAlignment'] = 'start';
          }
          children.addAll(_crawlThroughSliver(child));
        }
      });
  } catch (_) {}

  // CustomMultiChildLayout: 자식을 위치 기준으로 정렬
  if (isCustomMultiChild && children.length >= 2) {
    if (layoutMode == 'COLUMN') {
      children.sort((a, b) {
        final ay = (a['rect'] as Map<String, dynamic>?)?['y'] as double? ?? 0.0;
        final by = (b['rect'] as Map<String, dynamic>?)?['y'] as double? ?? 0.0;
        return ay.compareTo(by);
      });
    } else {
      children.sort((a, b) {
        final ax = (a['rect'] as Map<String, dynamic>?)?['x'] as double? ?? 0.0;
        final bx = (b['rect'] as Map<String, dynamic>?)?['x'] as double? ?? 0.0;
        return ax.compareTo(bx);
      });
    }
  }

  // ---------------------------------------------------
  // [10.5] TextField 구조 재편: bg를 입력 영역에만, 패딩 적용
  // ---------------------------------------------------
  if (isTextFieldNode && children.isNotEmpty) {
    // hint/text 중복 제거:
    // RenderEditable(실텍스트)이 먼저, RenderParagraph(hint)가 뒤에 옴.
    // 실텍스트가 비어있지 않으면 hint(두 번째) 제거.
    // 실텍스트가 비어있으면 실텍스트 제거하고 hint만 남김.
    final textKids = children.where((c) => c['type'] == 'Text').toList();
    if (textKids.length >= 2) {
      final first = textKids.first; // 실텍스트 (RenderEditable)
      final second = textKids.last; // hint (RenderParagraph)
      final firstContent =
          ((first['visual'] as Map?)?['content'] as String?) ?? '';
      if (firstContent.isNotEmpty) {
        // 실텍스트 있음 → hint 제거
        children.remove(second);
      } else {
        // 실텍스트 비어있음 → 실텍스트 제거, hint만 남김
        children.remove(first);
      }
    } else if (textKids.length == 1) {
      final v = textKids.first['visual'] as Map<String, dynamic>? ?? {};
      if (((v['content'] as String?) ?? '').isEmpty) {
        children.remove(textKids.first);
      }
    }

    // decoration box 찾기: 콘텐츠 없는 Frame, 부모와 비슷한 너비
    int decoIdx = -1;
    for (int i = children.length - 1; i >= 0; i--) {
      final c = children[i];
      if (c['type'] == 'Frame' && !_hasContentRecursive(c)) {
        final cr = c['rect'] as Map<String, dynamic>?;
        if (cr != null) {
          final cw = (cr['w'] as num?)?.toDouble() ?? 0;
          if (cw >= node.size.width * 0.9) {
            decoIdx = i;
            break;
          }
        }
      }
    }

    if (decoIdx >= 0) {
      final decoBox = children[decoIdx];
      final decoRect = decoBox['rect'] as Map<String, dynamic>;
      final decoY = (decoRect['y'] as num).toDouble();
      final decoH = (decoRect['h'] as num).toDouble();
      final decoW = (decoRect['w'] as num).toDouble();
      final decoBottom = decoY + decoH;

      // 자식을 입력 영역 안 vs 아래(에러/헬퍼)로 분리
      final List<Map<String, dynamic>> inputChildren = [];
      final List<Map<String, dynamic>> belowChildren = [];
      for (int i = 0; i < children.length; i++) {
        if (i == decoIdx) continue;
        final c = children[i];
        final cy = ((c['rect'] as Map?)?['y'] as num?)?.toDouble() ?? 0;
        if (cy >= decoBottom - 1) {
          belowChildren.add(c);
        } else {
          inputChildren.add(c);
        }
      }

      // contentPadding 계산 (첫 번째 콘텐츠 자식 좌표 기반)
      Map<String, dynamic>? paddingMap;
      for (final ic in inputChildren) {
        final icRect = ic['rect'] as Map<String, dynamic>?;
        if (icRect != null) {
          final icX = (icRect['x'] as num?)?.toDouble() ?? 0;
          final icY = (icRect['y'] as num?)?.toDouble() ?? 0;
          final icW = (icRect['w'] as num?)?.toDouble() ?? 0;
          final icH = (icRect['h'] as num?)?.toDouble() ?? 0;
          final padLeft = icX - (decoRect['x'] as num).toDouble();
          final padTop = icY - decoY;
          final padRight = decoW - padLeft - icW;
          final padBottom = decoH - padTop - icH;
          if (padLeft >= 0 && padTop >= 0) {
            paddingMap = {
              'top': padTop > 0 ? padTop : 0.0,
              'right': padRight > 0 ? padRight : 0.0,
              'bottom': padBottom > 0 ? padBottom : 0.0,
              'left': padLeft > 0 ? padLeft : 0.0,
            };
            break;
          }
        }
      }

      if (belowChildren.isNotEmpty) {
        // 에러/헬퍼 텍스트 있음 → 구조 재편
        // bg/border를 decoBox로 이동
        decoBox['visual'] = Map<String, dynamic>.from(visual);
        decoBox['children'] = inputChildren;
        decoBox['layoutMode'] = 'COLUMN';
        decoBox['containerLayout'] = <String, dynamic>{
          'mainAxisAlignment': 'center',
          'crossAxisAlignment': 'start',
          'mainAxisSize': 'min',
        };
        if (paddingMap != null) {
          (decoBox['containerLayout'] as Map<String, dynamic>)['padding'] =
              paddingMap;
        }

        // 외부 → 투명 COLUMN
        visual.clear();
        hasVisual = false;
        layoutMode = 'COLUMN';
        isLayoutNode = true;
        containerLayout['mainAxisAlignment'] = 'start';
        containerLayout['crossAxisAlignment'] = 'stretch';
        containerLayout['mainAxisSize'] = 'min';
        containerLayout['itemSpacing'] = 4.0;

        children.clear();
        children.add(decoBox);
        children.addAll(belowChildren);
      } else {
        // 에러 없음 → 현재 노드에 패딩 + 레이아웃 적용
        layoutMode = 'COLUMN';
        isLayoutNode = true;
        containerLayout['mainAxisAlignment'] = 'center';
        containerLayout['crossAxisAlignment'] = 'start';
        containerLayout['mainAxisSize'] = 'min';
        if (paddingMap != null) {
          containerLayout['padding'] = paddingMap;
        }
        children.removeAt(decoIdx);
      }
    }
  }

  // Flex: itemSpacing 계산 (첫 번째 순회에서 수집한 _gaps 사용)
  if (isFlex && _gaps.isNotEmpty) {
    // 모두 같으면 그 값, 다르면 가장 빈번한 값
    final allSame = _gaps.every((g) => g == _gaps.first);
    if (allSame) {
      containerLayout['itemSpacing'] = _gaps.first;
    } else {
      final freq = <double, int>{};
      for (final g in _gaps) freq[g] = (freq[g] ?? 0) + 1;
      double bestGap = _gaps.first;
      int bestCount = 0;
      freq.forEach((g, count) {
        if (count > bestCount) {
          bestGap = g;
          bestCount = count;
        }
      });
      containerLayout['itemSpacing'] = bestGap;
    }
  }

  // 배경 이미지를 synthetic Image child로 추가
  if (backgroundImagePath != null) {
    final bgChild = <String, dynamic>{
      'type': 'Image',
      'layoutMode': 'NONE',
      'rect': {
        'x': offset.dx,
        'y': offset.dy,
        'w': node.size.width,
        'h': node.size.height,
      },
      'visual': <String, dynamic>{
        'imagePath': backgroundImagePath,
        'imageFit': backgroundImageFit ?? 'cover',
      },
      'children': <Map<String, dynamic>>[],
    };
    children.insert(0, bgChild);
  }

  // ---------------------------------------------------
  // Smart Flattening (조건 강화)
  // ---------------------------------------------------
  final bool hasPadding = containerLayout.containsKey('padding');
  if (type == 'Frame' &&
      !hasVisual &&
      !_hasVisualProps(visual) &&
      !isLayoutNode &&
      !isSizedBox &&
      layoutMode == 'NONE' &&
      !hasPadding &&
      children.length == 1) {
    return children.first;
  }
  if (children.isEmpty &&
      !hasVisual &&
      !_hasVisualProps(visual) &&
      (node.size.width < 1 && node.size.height < 1)) {
    return null;
  }

  // ---------------------------------------------------
  // Visual Merge + Flatten: NONE 래퍼(DecoratedBox 등)의 visual을
  // 자식 Frame에 병합하여 auto-layout 체인 유지
  // ---------------------------------------------------
  if (type == 'Frame' &&
      layoutMode == 'NONE' &&
      !isLayoutNode &&
      children.length == 1 &&
      children.first['type'] == 'Frame') {
    final child = children.first;
    final childRect = child['rect'] as Map<String, dynamic>?;
    final childW = (childRect?['w'] as num?)?.toDouble() ?? 0;
    final childH = (childRect?['h'] as num?)?.toDouble() ?? 0;

    // 자식이 부모보다 유의미하게 작으면 → merge하지 않고 센터링 컨테이너로 전환
    if ((node.size.width - childW).abs() > 4 ||
        (node.size.height - childH).abs() > 4) {
      layoutMode = 'COLUMN';
      isLayoutNode = true;
      containerLayout['mainAxisAlignment'] = 'center';
      containerLayout['crossAxisAlignment'] = 'center';
      containerLayout['mainAxisSize'] = 'max';
      // fall through → 일반 노드로 반환
    } else {
      // 같은 크기 → 기존 visual merge
      final childVisual = child['visual'] as Map<String, dynamic>;

      // outer visual → child에 병합 (child 기존 값 우선)
      visual.forEach((key, value) {
        if (value != null && !childVisual.containsKey(key)) {
          childVisual[key] = value;
        }
      });

      // outer rect 유지 (바운딩 박스)
      child['rect'] = {
        'x': offset.dx,
        'y': offset.dy,
        'w': node.size.width,
        'h': node.size.height,
      };
      // widgetName 전파 (merge 시 소실 방지)
      if (_widgetNameByRenderObject.containsKey(node) &&
          !child.containsKey('widgetName')) {
        child['widgetName'] = _widgetNameByRenderObject[node];
      }
      return child;
    }
  }

  // ---------------------------------------------------
  // 최종 노드 반환 (새 스키마)
  // ---------------------------------------------------
  final result = <String, dynamic>{
    'type': type,
    'layoutMode': layoutMode,
    'rect': {
      'x': offset.dx,
      'y': offset.dy,
      'w': node.size.width,
      'h': node.size.height,
    },
    'visual': visual,
    'children': children,
  };
  if (containerLayout.isNotEmpty) result['containerLayout'] = containerLayout;
  if (_widgetNameByRenderObject.containsKey(node)) {
    result['widgetName'] = _widgetNameByRenderObject[node];
  }
  // childLayout은 부모가 설정 (위에서 이미 설정됨)
  return result;
}

/// =======================================================
/// 4. 겹친 화면 제거
/// =======================================================

/// 재귀적으로 Scaffold를 찾아 마지막 것만 남긴다.
/// Navigator 스택에 여러 페이지가 쌓여 있을 때,
/// 최상위(마지막) Scaffold만 보존.
Map<String, dynamic> _keepLastScaffold(Map<String, dynamic> root) {
  final children = root['children'] as List<Map<String, dynamic>>?;
  if (children == null || children.isEmpty) return root;

  // 현재 레벨에서 Scaffold 찾기
  final scaffoldIndices = <int>[];
  for (int i = 0; i < children.length; i++) {
    if (_containsScaffold(children[i])) {
      scaffoldIndices.add(i);
    }
  }

  if (scaffoldIndices.length > 1) {
    // 마지막 Scaffold가 있는 자식만 남기고 나머지 Scaffold 자식 제거
    final lastIdx = scaffoldIndices.last;
    final filtered = <Map<String, dynamic>>[];
    for (int i = 0; i < children.length; i++) {
      if (scaffoldIndices.contains(i) && i != lastIdx) continue;
      filtered.add(children[i]);
    }
    root['children'] = filtered;
  } else {
    // 이 레벨에 Scaffold가 0~1개면 자식으로 재귀
    for (final child in children) {
      _keepLastScaffold(child);
    }
  }
  return root;
}

bool _containsScaffold(Map<String, dynamic> node) {
  if (node['widgetName'] == 'Scaffold') return true;
  final children = node['children'] as List?;
  if (children == null) return false;
  for (final child in children) {
    if (child is Map<String, dynamic> && _containsScaffold(child)) return true;
  }
  return false;
}

/// =======================================================
/// 5. 외부 진입점
/// =======================================================

String figmaExtractorEntryPoint() {
  try {
    debugPrint('[FigmaCrawler] ===== START (v2) =====');
    _designInfoByRenderObject.clear();
    _svgBoxTargets.clear();
    _widgetNameByRenderObject.clear();
    _customPaintCaptures.clear();
    _blurInfoByRenderObject.clear();
    _rotationByRenderObject.clear();
    _shaderMaskWidgets.clear();
    _customPainterByRO.clear();
    // _shaderMaskGradients는 async phase에서 채워지므로 여기서 clear하지 않음

    final rootElement = WidgetsBinding.instance.renderViewElement;
    if (rootElement != null) {
      try {
        rootElement.visitChildren(_collectDesignInfoFromElements);
      } catch (e, st) {
        debugPrint('[FigmaCrawler] Step 1 ERROR: $e\n$st');
      }
    }

    final root = RendererBinding.instance.renderView;
    final List<Map<String, dynamic>> rootChildren = [];
    root.visitChildren((child) {
      final res = _crawl(child);
      if (res != null) rootChildren.add(res);
    });

    double maxWidth = 0.0;
    double maxHeight = 0.0;
    try {
      maxWidth = root.size.width;
      maxHeight = root.size.height;
    } catch (_) {}

    final ui.Size screenSize = ui.Size(
      maxWidth > 0 ? maxWidth : 390.0,
      maxHeight > 0 ? maxHeight : 844.0,
    );

    final data = <String, dynamic>{
      'type': 'Frame',
      'name': 'Flutter Screen',
      'layoutMode': 'COLUMN',
      'rect': {
        'x': 0.0,
        'y': 0.0,
        'w': screenSize.width,
        'h': screenSize.height,
      },
      'visual': {'backgroundColor': '#ffffffff'},
      'containerLayout': {
        'mainAxisAlignment': 'start',
        'crossAxisAlignment': 'stretch',
        'mainAxisSize': 'max',
        'itemSpacing': 0.0,
        'padding': {'top': 0.0, 'right': 0.0, 'bottom': 0.0, 'left': 0.0},
      },
      'children': rootChildren,
    };

    _keepLastScaffold(data);

    final result = jsonEncode(data);
    debugPrint('[FigmaCrawler] ===== DONE (${result.length} chars) =====');
    return result;
  } catch (e, st) {
    debugPrint('[FigmaCrawler] FATAL ERROR: $e\n$st');
    return jsonEncode({'error': e.toString(), 'stackTrace': st.toString()});
  }
}

/// =======================================================
/// 5.5. 스크롤 위치 수집
/// =======================================================

List<ScrollPosition> _collectScrollPositions(Element? rootElement) {
  final List<ScrollPosition> positions = [];
  if (rootElement == null) return positions;
  void visit(Element element) {
    final widget = element.widget;
    if (widget is Scrollable) {
      try {
        final scrollable = (element as StatefulElement).state as ScrollableState;
        positions.add(scrollable.position);
      } catch (_) {}
    }
    element.visitChildren(visit);
  }
  rootElement.visitChildren(visit);
  return positions;
}

/// =======================================================
/// 6. Async export (이미지 pre-capture 포함)
/// =======================================================

Future<String> _figmaExportWithImagesAsync() async {
  _imageDataByNode.clear();
  _customPaintCaptures.clear();
  _blurInfoByRenderObject.clear();
  _rotationByRenderObject.clear();
  _shaderMaskWidgets.clear();
  _shaderMaskGradients.clear();
  _customPainterByRO.clear();

  // Phase 0: Element tree 순회 → _customPaintCaptures 등록 (pre-capture에 필요)
  final rootElement = WidgetsBinding.instance.renderViewElement;
  if (rootElement != null) {
    try {
      rootElement.visitChildren(_collectDesignInfoFromElements);
    } catch (_) {}
  }

  final root = RendererBinding.instance.renderView;

  // Phase 0.3: ShaderMask gradient 추출 (render tree에서 캡처 후 픽셀 샘플링)
  await _extractShaderMaskGradients(root);

  // Phase 0.5: 스크롤 뷰 pre-scroll → viewport 밖 위젯도 paint 강제
  final scrollPositions = _collectScrollPositions(rootElement);
  final Map<ScrollPosition, double> originalOffsets = {};
  for (final pos in scrollPositions) {
    originalOffsets[pos] = pos.pixels;
  }
  for (final pos in scrollPositions) {
    if (pos.maxScrollExtent <= 0) continue;
    final viewportDim = pos.viewportDimension;
    double current = 0;
    while (current < pos.maxScrollExtent) {
      current = (current + viewportDim).clamp(0.0, pos.maxScrollExtent);
      pos.jumpTo(current);
      await WidgetsBinding.instance.endOfFrame;
      await _preCaptureImages(root);
    }
  }
  // 원래 스크롤 위치로 복원
  for (final pos in scrollPositions) {
    pos.jumpTo(originalOffsets[pos] ?? 0.0);
  }
  await WidgetsBinding.instance.endOfFrame;

  // Phase 1: async pre-capture (상단 viewport 위젯 포함)
  await _preCaptureImages(root);

  // Phase 2: 기존 sync 크롤 (figmaExtractorEntryPoint 재사용)
  // Note: figmaExtractorEntryPoint 내부에서 _customPaintCaptures를 다시 채우지만,
  //       _imageDataByNode는 유지되므로 캡처 이미지가 정상 사용됨
  final result = figmaExtractorEntryPoint();

  _imageDataByNode.clear(); // 메모리 해제
  return result;
}

/// CLI에서 호출: evaluate('figmaStartExportWithImages()')
void figmaStartExportWithImages() {
  _asyncExportBusy = true;
  _asyncExportResult = null;
  _figmaExportWithImagesAsync()
      .then((r) {
        _asyncExportResult = r;
        _asyncExportBusy = false;
      })
      .catchError((e) {
        _asyncExportResult = '{"error":"$e"}';
        _asyncExportBusy = false;
      });
}

/// CLI에서 폴링: evaluate('figmaGetExportResult()')
String? figmaGetExportResult() {
  if (_asyncExportBusy) return null;
  return _asyncExportResult;
}
""";

// =============================================================
// JSON-RPC 2.0 over WebSocket
// =============================================================

int _rpcId = 1;
final Map<int, Completer<dynamic>> _pending = {};

Future<dynamic> rpcCall(
  WebSocket ws,
  String method, [
  Map<String, dynamic>? params,
]) {
  final id = _rpcId++;
  final completer = Completer<dynamic>();
  _pending[id] = completer;

  final payload = <String, dynamic>{
    'jsonrpc': '2.0',
    'id': id,
    'method': method,
  };
  if (params != null) payload['params'] = params;

  ws.add(jsonEncode(payload));
  return completer.future.timeout(const Duration(seconds: 30));
}

void _onWsData(dynamic data) {
  try {
    final msg = jsonDecode(data as String);
    if (msg is Map<String, dynamic>) {
      final id = msg['id'];
      if (id is int && _pending.containsKey(id)) {
        final c = _pending.remove(id)!;
        if (msg.containsKey('error')) {
          c.completeError(Exception(jsonEncode(msg['error'])));
        } else {
          c.complete(msg['result']);
        }
      }
    }
  } catch (e) {
    _log('WS parse error: $e');
  }
}

// =============================================================
// 로깅
// =============================================================

void _log(String msg) => stderr.writeln(msg);

// =============================================================
// VM Service URI 자동 탐지
// =============================================================

/// Strategy 1 (가장 정확): ps에서 development-service 프로세스 찾기
/// → raw VM Service URI 추출 → HTTP redirect → DDS WS URI (토큰 포함)
Future<String?> _discoverViaDds() async {
  _log('[Discovery] ps에서 development-service 프로세스 탐색...');

  final ps = await Process.run('ps', ['-eo', 'pid,args']);
  final lines = (ps.stdout as String).split('\n');

  String? rawVmUri;
  for (final line in lines) {
    if (!line.contains('development-service')) continue;
    if (line.contains('grep')) continue;
    final match = RegExp(r'vm-service-uri=(http://[^\s]+)').firstMatch(line);
    if (match != null) {
      rawVmUri = match.group(1)!;
      _log('[Discovery] Raw VM Service URI: $rawVmUri');
      break;
    }
  }

  if (rawVmUri == null) return null;

  // HTTP GET → redirect 따라가서 DDS WS URI 얻기
  _log('[Discovery] HTTP redirect 추적 중...');
  final client = HttpClient();
  client.connectionTimeout = const Duration(seconds: 5);

  try {
    final request = await client.getUrl(Uri.parse(rawVmUri));
    request.followRedirects = false;
    final response = await request.close();
    // body 소비
    await response.drain<void>();

    _log('[Discovery] HTTP ${response.statusCode}');

    if (response.statusCode == 302 || response.statusCode == 301) {
      final redirectUrl = response.headers.value('location');
      _log('[Discovery] Redirect → $redirectUrl');
      if (redirectUrl != null) {
        final wsUri = Uri.parse(redirectUrl).queryParameters['uri'];
        if (wsUri != null) {
          _log('[Discovery] DDS WS URI: $wsUri');
          return wsUri;
        }
      }
    }
  } catch (e) {
    _log('[Discovery] HTTP 요청 실패: $e');
  } finally {
    client.close();
  }

  // redirect 실패 시 raw URI를 ws로 변환해서 시도
  var fallback = rawVmUri
      .replaceFirst('http://', 'ws://')
      .replaceFirst('https://', 'wss://');
  if (!fallback.endsWith('/ws')) {
    fallback = fallback.endsWith('/') ? '${fallback}ws' : '$fallback/ws';
  }
  _log('[Discovery] Redirect 실패 → fallback: $fallback');
  return fallback;
}

/// Strategy 2 (fallback): lsof로 Dart 프로세스 포트 스캔
Future<String?> _scanDartPorts() async {
  _log('[Discovery] lsof 포트 스캔...');
  try {
    final result = await Process.run('lsof', ['-i', '-P', '-n']);
    for (final line in (result.stdout as String).split('\n')) {
      if (!line.toLowerCase().contains('dart')) continue;
      if (!line.contains('LISTEN')) continue;
      final m = RegExp(r':(\d+)\s+\(LISTEN\)').firstMatch(line);
      if (m != null) {
        final uri = 'ws://127.0.0.1:${m.group(1)}/ws';
        _log('[Discovery] lsof에서 포트 발견: $uri');
        return uri;
      }
    }
  } catch (_) {}
  return null;
}

Future<String?> discoverVmServiceUri() async {
  _log('[Discovery] VM Service 자동 탐색 중...');

  // 1차: DDS 프로세스 → redirect → 정확한 WS URI (토큰 포함)
  final fromDds = await _discoverViaDds();
  if (fromDds != null) return fromDds;

  // 2차: lsof 포트 스캔 (토큰 없이 시도, --disable-service-auth-codes 필요)
  final fromPort = await _scanDartPorts();
  if (fromPort != null) return fromPort;

  return null;
}

// =============================================================
// 크롤러 주입 (내장 소스 → 파일 생성 + import 추가)
// =============================================================

/// 크롤러 주입. 이미 주입돼 있으면 false, 새로 주입하면 true 반환.
bool injectCrawler(String projectPath) {
  final destPath = '$projectPath/lib/figma_temp_crawler.dart';
  final mainPath = '$projectPath/lib/main.dart';

  if (!File(mainPath).existsSync()) {
    throw Exception('$mainPath 파일을 찾을 수 없습니다.');
  }

  // 내장 소스를 파일로 쓰기 (항상 최신으로 덮어쓰기)
  File(destPath).writeAsStringSync(_crawlerSource);
  _log('[Inject] 크롤러 생성 → $destPath');

  // main.dart에 import 추가
  var mainCode = File(mainPath).readAsStringSync();
  if (mainCode.contains("import 'figma_temp_crawler.dart'")) {
    _log('[Inject] import 이미 존재 → hot reload 불필요');
    return false;
  }

  final importRe = RegExp('^import\\s+[\\x27\\x22].*[\\x27\\x22];?\\s*\$', multiLine: true);
  final matches = importRe.allMatches(mainCode).toList();
  if (matches.isNotEmpty) {
    final end = matches.last.end;
    mainCode = '${mainCode.substring(0, end)}'
        "\nimport 'figma_temp_crawler.dart';\n"
        '${mainCode.substring(end)}';
  } else {
    mainCode = "import 'figma_temp_crawler.dart';\n$mainCode";
  }

  File(mainPath).writeAsStringSync(mainCode);
  _log('[Inject] main.dart에 import 추가 완료');
  return true;
}

// =============================================================
// 메인
// =============================================================

Future<void> main(List<String> args) async {
  final projectPath = Directory.current.path;
  _log('========================================');
  _log(' Flutter → Figma Layout Exporter');
  _log('========================================');
  _log('[Project] $projectPath');

  // ---- VM Service URI ----
  String? vmUri;
  if (args.isNotEmpty) {
    vmUri = args[0];
    _log('[URI] 수동 지정: $vmUri');
  } else {
    vmUri = await discoverVmServiceUri();
  }
  if (vmUri == null) {
    _log('');
    _log('[ERROR] 실행 중인 Flutter 앱을 찾을 수 없습니다.');
    _log('');
    _log('해결 방법:');
    _log('  1) Flutter 앱을 디버그 모드로 먼저 실행하세요.');
    _log('  2) 콘솔에 출력된 VM Service URI를 인자로 전달하세요:');
    _log('     dart tools/export_figma_layout.dart ws://127.0.0.1:PORT/TOKEN=/ws');
    exit(1);
  }

  // ---- 크롤러 주입 ----
  final needsReload = injectCrawler(projectPath);

  // ---- WebSocket 연결 ----
  _log('[Connect] $vmUri');
  late WebSocket ws;
  try {
    ws = await WebSocket.connect(vmUri);
  } catch (e) {
    _log('[ERROR] WebSocket 연결 실패: $e');
    _log('URI가 올바른지, Flutter 앱이 디버그 모드로 실행 중인지 확인하세요.');
    exit(1);
  }
  ws.listen(_onWsData, onError: (e) => _log('[WS ERROR] $e'));

  try {
    // ---- getVM → isolateId ----
    final vm = await rpcCall(ws, 'getVM') as Map<String, dynamic>;
    final isolates =
        (vm['isolates'] as List).cast<Map<String, dynamic>>();
    if (isolates.isEmpty) throw Exception('VM에 isolate가 없습니다.');
    final isolateId = isolates[0]['id'] as String;
    _log('[VM] isolate: $isolateId');

    // ---- Hot Reload (필요 시) ----
    if (needsReload) {
      _log('[HotReload] reloadSources 호출 중...');
      await rpcCall(ws, 'reloadSources', {'isolateId': isolateId});
      await Future.delayed(const Duration(seconds: 3));
      _log('[HotReload] 완료');
    }

    // ---- 크롤러 라이브러리 찾기 ----
    final iso = await rpcCall(ws, 'getIsolate', {'isolateId': isolateId})
        as Map<String, dynamic>;
    final libs =
        (iso['libraries'] as List).cast<Map<String, dynamic>>();
    final crawlerLib = libs.cast<Map<String, dynamic>?>().firstWhere(
          (l) => (l!['uri'] as String).contains('figma_temp_crawler'),
          orElse: () => null,
        );

    await Future.delayed(const Duration(milliseconds: 1500));

    // ---- evaluate (이미지 포함 async export 시도) ----
    _log('[Evaluate] figmaStartExportWithImages() 호출...');
    dynamic result;
    if (crawlerLib != null) {
      try {
        // Phase 1: async export 시작
        await rpcCall(ws, 'evaluate', {
          'isolateId': isolateId,
          'targetId': crawlerLib['id'],
          'expression': 'figmaStartExportWithImages()',
        });

        // Phase 2: 결과 폴링 (최대 30초)
        for (int i = 0; i < 60; i++) {
          await Future.delayed(const Duration(milliseconds: 500));
          final pollResult = await rpcCall(ws, 'evaluate', {
            'isolateId': isolateId,
            'targetId': crawlerLib['id'],
            'expression': 'figmaGetExportResult()',
          }) as Map<String, dynamic>;
          if (pollResult['valueAsString'] != null &&
              pollResult['valueAsString'] != 'null') {
            result = pollResult;
            _log('[Evaluate] async export 완료 (${i * 500}ms)');
            break;
          }
        }

        // 폴링 타임아웃 시 sync fallback
        if (result == null) {
          _log('[Evaluate] async export 타임아웃 → sync fallback');
          result = await rpcCall(ws, 'evaluate', {
            'isolateId': isolateId,
            'targetId': crawlerLib['id'],
            'expression': 'figmaExtractorEntryPoint()',
          });
        }
      } catch (_) {
        _log('[Evaluate] 라이브러리 컨텍스트 실패 → 전역 컨텍스트 재시도');
        result = await rpcCall(ws, 'evaluate', {
          'isolateId': isolateId,
          'expression': 'figmaExtractorEntryPoint()',
        });
      }
    } else {
      result = await rpcCall(ws, 'evaluate', {
        'isolateId': isolateId,
        'expression': 'figmaExtractorEntryPoint()',
      });
    }

    // ---- 결과 추출 (truncation 처리) ----
    final res = result as Map<String, dynamic>;
    String jsonString;
    if (res['valueAsString'] != null &&
        res['valueAsStringIsTruncated'] != true) {
      jsonString = res['valueAsString'] as String;
    } else if (res['id'] != null) {
      _log('[Evaluate] 결과가 잘림 → getObject로 전체 가져오기...');
      final full = await rpcCall(ws, 'getObject', {
        'isolateId': isolateId,
        'objectId': res['id'],
      }) as Map<String, dynamic>;
      jsonString = full['valueAsString'] as String;
    } else {
      throw Exception('예상치 못한 결과: ${jsonEncode(result)}');
    }

    // ---- 저장 ----
    final dumpDir = Directory('$projectPath/flutter_figma_dump');
    if (!dumpDir.existsSync()) dumpDir.createSync(recursive: true);

    File('${dumpDir.path}/figma_layout_raw.json')
        .writeAsStringSync(jsonString);

    final data = jsonDecode(jsonString);
    final pretty = const JsonEncoder.withIndent('  ').convert(data);
    File('${dumpDir.path}/figma_layout.json').writeAsStringSync(pretty);

    // 클립보드 (macOS)
    try {
      final pb = await Process.start('pbcopy', []);
      pb.stdin.write(pretty);
      await pb.stdin.close();
      await pb.exitCode;
      _log('[Done] 클립보드에 복사 완료');
    } catch (_) {}

    _log('[Done] 저장 → flutter_figma_dump/figma_layout.json');
    _log('[Done] JSON 길이: ${jsonString.length} chars');
    _log('========================================');
  } finally {
    await ws.close();
  }
}
