// tools/crawler_source.dart
// 크롤러의 단일 진실 소스 (Single Source of Truth)
// IDE에서 직접 편집 가능. merge.dart로 빌드 후 사용.
//
// figma_temp_crawler.dart (auto-generated by export_figma_layout.dart)
// Schema v2: explicit layoutMode, childLayout, containerLayout, visual

import 'dart:convert';
import 'dart:ui' as ui;
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';

/// =======================================================
/// 0. 유틸 & 전역 상태
/// =======================================================

String? _colorToHex(Color? color) {
  if (color == null) return null;
  return '#' + color.value.toRadixString(16).padLeft(8, '0');
}

class DesignInfo {
  final Color? backgroundColor;
  final Color? borderColor;
  final double? borderWidth;
  final double? borderRadius;
  final double? elevation;
  final bool isTextField;
  final bool isDivider;

  DesignInfo({
    this.backgroundColor,
    this.borderColor,
    this.borderWidth,
    this.borderRadius,
    this.elevation,
    this.isTextField = false,
    this.isDivider = false,
  });
}

final Map<RenderObject, DesignInfo> _designInfoByRenderObject = {};
final Set<RenderObject> _svgBoxTargets = {};
final Map<RenderObject, String> _imageDataByNode = {};
String? _asyncExportResult;
bool _asyncExportBusy = false;

/// =======================================================
/// 0.5 Pre-capture: 이미지/아이콘 → base64 (async)
/// =======================================================

Future<void> _preCaptureImages(RenderObject node) async {
  // RenderImage → 축소 후 PNG 인코딩 (최대 512px)
  if (node is RenderImage) {
    try {
      final ui.Image? img = node.image;
      if (img != null) {
        final maxDim = 512;
        int targetW = img.width;
        int targetH = img.height;
        if (targetW > maxDim || targetH > maxDim) {
          final scale = maxDim / (targetW > targetH ? targetW : targetH);
          targetW = (targetW * scale).ceil();
          targetH = (targetH * scale).ceil();
        }
        final recorder = ui.PictureRecorder();
        final canvas = Canvas(recorder);
        canvas.drawImageRect(
          img,
          Rect.fromLTWH(0, 0, img.width.toDouble(), img.height.toDouble()),
          Rect.fromLTWH(0, 0, targetW.toDouble(), targetH.toDouble()),
          Paint(),
        );
        final picture = recorder.endRecording();
        final resized = await picture.toImage(targetW, targetH);
        final byteData = await resized.toByteData(format: ui.ImageByteFormat.png);
        if (byteData != null) {
          _imageDataByNode[node] = base64Encode(byteData.buffer.asUint8List());
        }
      }
    } catch (_) {}
  }

  // MaterialIcons → TextPainter → PictureRecorder → toImage()
  if (node is RenderParagraph) {
    try {
      final span = node.text;
      if (span is TextSpan && span.style?.fontFamily?.contains('MaterialIcons') == true) {
        final recorder = ui.PictureRecorder();
        final canvas = Canvas(
          recorder,
          Rect.fromLTWH(0, 0, node.size.width, node.size.height),
        );
        final painter = TextPainter(
          text: span,
          textDirection: TextDirection.ltr,
        );
        painter.layout();
        painter.paint(canvas, Offset.zero);
        final picture = recorder.endRecording();
        final img = await picture.toImage(
          node.size.width.ceil(),
          node.size.height.ceil(),
        );
        final byteData = await img.toByteData(format: ui.ImageByteFormat.png);
        if (byteData != null) {
          _imageDataByNode[node] = base64Encode(byteData.buffer.asUint8List());
        }
      }
    } catch (_) {}
  }

  // 자식 재귀 (visitChildren은 sync callback → 리스트 수집 후 순회)
  final children = <RenderObject>[];
  node.visitChildren((child) => children.add(child));
  for (final child in children) {
    await _preCaptureImages(child);
  }
}

/// =======================================================
/// 1. Element 트리 순회해서 위젯 레벨 디자인 정보 수집
/// =======================================================

void _collectDesignInfoFromElements(Element element) {
  final widget = element.widget;

  if (widget is InputDecorator) {
    final InputDecoration deco = widget.decoration;
    Color? bg;
    Color? borderColor;
    double? borderWidth;
    double? radius;

    if (deco.filled == true) {
      bg = deco.fillColor;
    }

    final InputBorder? border =
        deco.enabledBorder ?? deco.focusedBorder ?? deco.border;

    if (border is OutlineInputBorder) {
      final side = border.borderSide;
      borderColor = side.color;
      borderWidth = side.width;
      final br = border.borderRadius;
      if (br is BorderRadius) {
        radius = br.topLeft.x;
      }
    }

    final ro = element.renderObject;
    if (ro != null && (bg != null || borderColor != null || radius != null)) {
      _designInfoByRenderObject[ro] = DesignInfo(
        backgroundColor: bg,
        borderColor: borderColor,
        borderWidth: borderWidth,
        borderRadius: radius,
        isTextField: true,
      );
    }
  }

  if (widget is Divider) {
    final ro = element.renderObject;
    if (ro != null && widget.color != null) {
      _designInfoByRenderObject[ro] = DesignInfo(
        backgroundColor: widget.color,
        isDivider: true,
      );
    }
  }

  if (widget is Container) {
    final deco = widget.decoration;
    Color? bg;
    Color? borderColor;
    double? borderWidth;
    double? radius;

    if (deco is BoxDecoration) {
      bg = deco.color;
      final border = deco.border;
      if (border is Border) {
        final side = border.top;
        borderColor = side.color;
        borderWidth = side.width;
      }
      final br = deco.borderRadius;
      if (br is BorderRadius) {
        radius = br.topLeft.x;
      }
    }

    final ro = element.renderObject;
    if (ro != null && (bg != null || borderColor != null)) {
      _designInfoByRenderObject[ro] = DesignInfo(
        backgroundColor: bg,
        borderColor: borderColor,
        borderWidth: borderWidth,
        borderRadius: radius,
      );
    }
  }

  if (widget.runtimeType.toString().contains('SvgPicture')) {
    final ro = element.renderObject;
    if (ro != null) {
      _svgBoxTargets.add(ro);
    }
  }

  element.visitChildren(_collectDesignInfoFromElements);
}

/// =======================================================
/// 2. 헬퍼: visual 속성 추출
/// =======================================================

/// borderRadius 문자열에서 숫자 추출
double? _parseBorderRadius(dynamic br) {
  if (br == null) return null;
  final s = br.toString();
  if (s.contains('zero')) return 0.0;
  final m = RegExp(r'\d+\.?\d*').firstMatch(s);
  if (m != null) return double.tryParse(m.group(0)!);
  return double.tryParse(s);
}

/// visual 속성이 있는지 (배경, 테두리, 그림자 등)
bool _hasVisualProps(Map<String, dynamic> visual) {
  return visual['backgroundColor'] != null ||
      (visual['border'] != null) ||
      (visual['shadow'] != null) ||
      visual['borderRadius'] != null ||
      visual['isIconBox'] == true ||
      visual['isSvgBox'] == true ||
      visual['isTextField'] == true ||
      visual['isDivider'] == true;
}

/// =======================================================
/// 3. Render 트리 크롤러 (Schema v2)
/// =======================================================

/// SliverPadding에서 패딩을 추출하여 containerLayout에 저장
void _extractSliverPadding(RenderObject sliver, Map<String, dynamic> cl) {
  if (sliver is RenderSliverPadding) {
    final EdgeInsets? resolved = sliver.resolvedPadding;
    if (resolved != null && !cl.containsKey('padding')) {
      cl['padding'] = {
        'top': resolved.top,
        'right': resolved.right,
        'bottom': resolved.bottom,
        'left': resolved.left,
      };
    }
  }
  sliver.visitChildren((child) {
    if (child is! RenderBox) {
      _extractSliverPadding(child, cl);
    }
  });
}

List<Map<String, dynamic>> _crawlThroughSliver(RenderObject sliver) {
  final List<Map<String, dynamic>> results = [];
  sliver.visitChildren((child) {
    if (child is RenderBox) {
      final res = _crawl(child);
      if (res != null) results.add(res);
    } else {
      results.addAll(_crawlThroughSliver(child));
    }
  });
  return results;
}

/// 메인 크롤 함수: RenderObject → 새 스키마 노드
Map<String, dynamic>? _crawl(RenderObject? node) {
  if (node == null) return null;

  // Sliver 노드: 통과하여 내부 RenderBox 수집
  if (node is! RenderBox) {
    final sliverChildren = _crawlThroughSliver(node);
    if (sliverChildren.isEmpty) return null;
    if (sliverChildren.length == 1) return sliverChildren.first;
    return {
      'type': 'Frame',
      'layoutMode': 'COLUMN',
      'rect': sliverChildren.first['rect'],
      'visual': <String, dynamic>{},
      'containerLayout': <String, dynamic>{},
      'children': sliverChildren,
    };
  }

  if (!node.hasSize) return null;
  if (node.size.width == 0 && node.size.height == 0) return null;
  if (node is RenderOffstage && node.offstage) return null;

  Offset offset;
  try {
    offset = node.localToGlobal(Offset.zero);
  } catch (_) {
    return null;
  }

  // 기본값
  String type = 'Frame';
  String layoutMode = 'NONE';
  final Map<String, dynamic> visual = {};
  final Map<String, dynamic> containerLayout = {};
  bool hasVisual = false;
  bool isLayoutNode = false;
  bool isSizedBox = false;
  bool isCustomMultiChild = false;

  final String runtimeTypeStr = node.runtimeType.toString();
  final bool isSvgBoxTarget = _svgBoxTargets.contains(node);

  String? backgroundImagePath;
  String? backgroundImageFit;

  // ---------------------------------------------------
  // [0] SvgPicture placeholder
  // ---------------------------------------------------
  if (isSvgBoxTarget) {
    hasVisual = true;
    visual['backgroundColor'] = '#ffdddddd';
    visual['isSvgBox'] = true;
  }
  // ---------------------------------------------------
  // [1] Text / Icon
  // ---------------------------------------------------
  else if (node is RenderParagraph) {
    TextStyle? style;
    InlineSpan inlineSpan = node.text;
    if (inlineSpan is TextSpan) {
      style = inlineSpan.style;
    }
    final String? fontFamily = style?.fontFamily;

    if (fontFamily != null && fontFamily.contains('MaterialIcons')) {
      type = 'Frame';
      hasVisual = true;
      final Color color = style?.color ?? const Color(0xFF000000);
      visual['backgroundColor'] = _colorToHex(color);
      visual['isIconBox'] = true;
      // pre-captured 아이콘 이미지 lookup
      final b64 = _imageDataByNode[node];
      if (b64 != null) {
        visual['iconImageBase64'] = b64;
      }
    } else {
      type = 'Text';
      hasVisual = true;
      try {
        visual['content'] = node.text.toPlainText();
        visual['textAlign'] = node.textAlign.toString().split('.').last;
        if (style != null) {
          visual['fontFamily'] = style.fontFamily;
          visual['fontSize'] = style.fontSize;
          visual['fontWeight'] = style.fontWeight.toString();
          visual['color'] = _colorToHex(style.color);
          visual['letterSpacing'] = style.letterSpacing;
        }
      } catch (_) {}
    }
  }
  // ---------------------------------------------------
  // [2] Image
  // ---------------------------------------------------
  else if (node is RenderImage) {
    type = 'Image';
    hasVisual = true;
    try {
      visual['imagePath'] = node.debugImageLabel;
      visual['imageFit'] = 'cover';
      // pre-captured 이미지 데이터 lookup
      final b64 = _imageDataByNode[node];
      if (b64 != null) {
        visual['imageBase64'] = b64;
      }
    } catch (_) {}
  }
  // ---------------------------------------------------
  // [2.5] Padding (RenderPadding) — 자식에 병합
  // ---------------------------------------------------
  else if (node is RenderPadding) {
    final EdgeInsetsGeometry resolvedPadding = node.padding;
    EdgeInsets insets;
    if (resolvedPadding is EdgeInsets) {
      insets = resolvedPadding;
    } else {
      insets = resolvedPadding.resolve(TextDirection.ltr);
    }

    final paddingMap = {
      'top': insets.top,
      'right': insets.right,
      'bottom': insets.bottom,
      'left': insets.left,
    };

    RenderBox? singleChild;
    int childCount = 0;
    node.visitChildren((child) {
      childCount++;
      if (child is RenderBox) singleChild = child;
    });

    // Padding + RenderFlex → padding을 Flex containerLayout에 병합
    if (childCount == 1 && singleChild is RenderFlex) {
      final flexResult = _crawl(singleChild);
      if (flexResult != null) {
        final cl = flexResult['containerLayout'] as Map<String, dynamic>? ?? {};
        cl['padding'] = paddingMap;
        flexResult['containerLayout'] = cl;
        flexResult['rect'] = {
          'x': offset.dx,
          'y': offset.dy,
          'w': node.size.width,
          'h': node.size.height,
        };
        return flexResult;
      }
    }

    // Padding + RenderStack → padding을 Stack containerLayout에 병합
    if (childCount == 1 && singleChild is RenderStack) {
      final stackResult = _crawl(singleChild);
      if (stackResult != null) {
        final cl =
            stackResult['containerLayout'] as Map<String, dynamic>? ?? {};
        cl['padding'] = paddingMap;
        stackResult['containerLayout'] = cl;
        stackResult['rect'] = {
          'x': offset.dx,
          'y': offset.dy,
          'w': node.size.width,
          'h': node.size.height,
        };
        return stackResult;
      }
    }

    // 기타: Frame(COLUMN) + padding
    // RenderPadding은 tight constraints를 자식에게 전달 → stretch가 올바른 매핑
    type = 'Frame';
    layoutMode = 'COLUMN';
    isLayoutNode = true;
    containerLayout['padding'] = paddingMap;
    containerLayout['mainAxisAlignment'] = 'start';
    containerLayout['crossAxisAlignment'] = 'stretch';
    containerLayout['mainAxisSize'] = 'min';
    containerLayout['itemSpacing'] = 0.0;
  }
  // ---------------------------------------------------
  // [3] RenderStack (신규)
  // ---------------------------------------------------
  else if (node is RenderStack) {
    type = 'Frame';
    layoutMode = 'STACK';
    isLayoutNode = true;
  }
  // ---------------------------------------------------
  // [3.5] RenderPositionedBox (Align / Center / Container.alignment)
  // ---------------------------------------------------
  else if (node is RenderPositionedBox) {
    type = 'Frame';
    isLayoutNode = true;
    layoutMode = 'COLUMN';

    final alignment = node.alignment;
    Alignment resolved;
    if (alignment is Alignment) {
      resolved = alignment;
    } else {
      resolved = alignment.resolve(TextDirection.ltr);
    }

    // alignment.y → mainAxisAlignment (COLUMN = vertical)
    String mainAlign;
    if (resolved.y <= -0.5) {
      mainAlign = 'start';
    } else if (resolved.y >= 0.5) {
      mainAlign = 'end';
    } else {
      mainAlign = 'center';
    }

    // alignment.x → crossAxisAlignment (COLUMN = horizontal)
    String crossAlign;
    if (resolved.x <= -0.5) {
      crossAlign = 'start';
    } else if (resolved.x >= 0.5) {
      crossAlign = 'end';
    } else {
      crossAlign = 'center';
    }

    containerLayout['mainAxisAlignment'] = mainAlign;
    containerLayout['crossAxisAlignment'] = crossAlign;
    containerLayout['mainAxisSize'] = 'max';
  }
  // ---------------------------------------------------
  // [4] RenderConstrainedBox (SizedBox)
  // ---------------------------------------------------
  else if (node is RenderConstrainedBox) {
    isSizedBox = true;
    // 자식 확인
    RenderBox? singleChild;
    int childCount = 0;
    node.visitChildren((child) {
      childCount++;
      if (child is RenderBox) singleChild = child;
    });

    if (childCount == 1 && singleChild != null) {
      // 자식 있으면 투과 — 크기 정보만 childLayout에서 처리
      final childResult = _crawl(singleChild);
      if (childResult != null) {
        // rect를 SizedBox 기준으로 업데이트
        childResult['rect'] = {
          'x': offset.dx,
          'y': offset.dy,
          'w': node.size.width,
          'h': node.size.height,
        };
        // Tight constraints → fixedSize / fixedWidth / fixedHeight 마킹
        // 렌더 크기 ≈ 제약 크기일 때만 (Expanded 안 SizedBox 제외)
        final ac = node.additionalConstraints;
        final cl = childResult['childLayout'] as Map<String, dynamic>? ?? {};
        bool marked = false;
        if (ac.hasTightWidth && ac.maxWidth.isFinite) {
          if ((node.size.width - ac.maxWidth).abs() < 1.0) {
            cl['fixedWidth'] = true;
            marked = true;
          }
        }
        if (ac.hasTightHeight && ac.maxHeight.isFinite) {
          if ((node.size.height - ac.maxHeight).abs() < 1.0) {
            cl['fixedHeight'] = true;
            marked = true;
          }
        }
        if (cl['fixedWidth'] == true && cl['fixedHeight'] == true) {
          cl['fixedSize'] = true;
        }
        if (marked) {
          childResult['childLayout'] = cl;
        }
        return childResult;
      }
    }

    // 자식 없으면 Spacer 역할 (빈 Frame)
    type = 'Frame';
    layoutMode = 'NONE';
  }
  // ---------------------------------------------------
  // [5] Flex (Row / Column)
  // ---------------------------------------------------
  else if (node is RenderFlex) {
    type = 'Frame';
    isLayoutNode = true;
    layoutMode = node.direction == Axis.horizontal ? 'ROW' : 'COLUMN';

    final mainAlign = node.mainAxisAlignment.toString().split('.').last;
    final crossAlign = node.crossAxisAlignment.toString().split('.').last;
    final mainSize = node.mainAxisSize == MainAxisSize.min ? 'min' : 'max';

    containerLayout['mainAxisAlignment'] = mainAlign;
    containerLayout['crossAxisAlignment'] = crossAlign;
    containerLayout['mainAxisSize'] = mainSize;
  }
  // ---------------------------------------------------
  // [5.5] RenderWrap
  // ---------------------------------------------------
  else if (node is RenderWrap) {
    type = 'Frame';
    isLayoutNode = true;
    layoutMode = 'WRAP';
    containerLayout['itemSpacing'] = node.spacing;
    containerLayout['runSpacing'] = node.runSpacing;
    containerLayout['mainAxisAlignment'] =
        node.alignment.toString().split('.').last;
    containerLayout['crossAxisAlignment'] =
        node.crossAxisAlignment.toString().split('.').last;
  }
  // ---------------------------------------------------
  // [6] DecoratedBox
  // ---------------------------------------------------
  else if (node is RenderDecoratedBox) {
    type = 'Frame';
    try {
      final decoration = node.decoration;
      if (decoration is BoxDecoration) {
        if (decoration.color != null) {
          visual['backgroundColor'] = _colorToHex(decoration.color);
          hasVisual = true;
        }
        if (decoration.image != null) {
          final DecorationImage decorationImage = decoration.image!;
          final ImageProvider provider = decorationImage.image;
          if (provider is AssetImage) {
            backgroundImagePath = provider.assetName;
            backgroundImageFit = decorationImage.fit?.toString();
            hasVisual = true;
          }
        }
        if (decoration.border != null) {
          final border = decoration.border;
          if (border is Border) {
            final sides = [
              border.top,
              border.right,
              border.bottom,
              border.left,
            ];
            BorderSide? bestSide;
            for (final side in sides) {
              if (side.width > 0) {
                bestSide = side;
                break;
              }
            }
            if (bestSide != null) {
              visual['border'] = {
                'color': _colorToHex(bestSide.color),
                'width': bestSide.width,
              };
              hasVisual = true;
            }
          } else {
            visual['border'] = {'color': '#ff000000', 'width': 1.0};
            hasVisual = true;
          }
        }
        // BoxShape.circle → borderRadius = shortestSide / 2
        if (decoration.shape == BoxShape.circle) {
          visual['borderRadius'] = node.size.shortestSide / 2;
        } else {
          final br = _parseBorderRadius(decoration.borderRadius);
          if (br != null) visual['borderRadius'] = br;
        }
        if (decoration.boxShadow != null && decoration.boxShadow!.isNotEmpty) {
          final s = decoration.boxShadow!.first;
          visual['shadow'] = {
            'color': _colorToHex(s.color),
            'offsetX': s.offset.dx,
            'offsetY': s.offset.dy,
            'blurRadius': s.blurRadius,
            'spreadRadius': s.spreadRadius,
          };
          hasVisual = true;
        }
      }
    } catch (_) {}
  }
  // ---------------------------------------------------
  // [7] PhysicalModel
  // ---------------------------------------------------
  else if (node is RenderPhysicalModel) {
    type = 'Frame';
    hasVisual = true;
    visual['backgroundColor'] = _colorToHex(node.color);
    if (node.elevation > 0) {
      visual['shadow'] = {'elevation': node.elevation};
    }
    try {
      dynamic d = node;
      if (d.borderRadius != null) {
        final br = _parseBorderRadius(d.borderRadius);
        if (br != null) visual['borderRadius'] = br;
      }
    } catch (_) {}
  }
  // ---------------------------------------------------
  // [8] PhysicalShape
  // ---------------------------------------------------
  else if (node is RenderPhysicalShape) {
    type = 'Frame';
    hasVisual = true;
    visual['backgroundColor'] = _colorToHex(node.color);
    if (node.elevation > 0) {
      visual['shadow'] = {'elevation': node.elevation};
    }
    try {
      final diagnostics = node.toDiagnosticsNode();
      final properties = diagnostics.getProperties();
      final clipperProp = properties.firstWhere(
        (p) => p.name == 'clipper',
        orElse: () => DiagnosticsProperty('dummy', null),
      );
      if (clipperProp.value != null) {
        dynamic clipper = clipperProp.value;
        dynamic shape = clipper.shape;
        final shapeStr = shape.toString();
        final reg = RegExp(r'circular\(([\d\.]+)\)');
        final m = reg.firstMatch(shapeStr);
        if (m != null) {
          visual['borderRadius'] = double.tryParse(m.group(1)!) ?? 0.0;
        }
      }
    } catch (_) {}
  }
  // ---------------------------------------------------
  // [8.5] RenderClipRRect
  // ---------------------------------------------------
  else if (node is RenderClipRRect) {
    final br = _parseBorderRadius(node.borderRadius);
    RenderBox? singleChild;
    int childCount = 0;
    node.visitChildren((child) {
      childCount++;
      if (child is RenderBox) singleChild = child;
    });
    if (childCount == 1 && singleChild != null) {
      final childResult = _crawl(singleChild);
      if (childResult != null) {
        if (br != null && br > 0) {
          final childVisual = childResult['visual'] as Map<String, dynamic>? ?? {};
          if (!childVisual.containsKey('borderRadius')) {
            childVisual['borderRadius'] = br;
            childResult['visual'] = childVisual;
          }
        }
        childResult['rect'] = {
          'x': offset.dx, 'y': offset.dy,
          'w': node.size.width, 'h': node.size.height,
        };
        return childResult;
      }
    }
    type = 'Frame';
    layoutMode = 'NONE';
    if (br != null && br > 0) visual['borderRadius'] = br;
  }
  // ---------------------------------------------------
  // [9] Picture / CustomPaint
  // ---------------------------------------------------
  else if (runtimeTypeStr.contains('Picture') ||
      runtimeTypeStr.contains('CustomPaint')) {
    type = 'Frame';
    hasVisual = false;
  }
  // ---------------------------------------------------
  // [9.5] CustomMultiChildLayout (NavigationToolbar, Scaffold 등)
  // ---------------------------------------------------
  else if (runtimeTypeStr.contains('CustomMultiChildLayoutBox')) {
    type = 'Frame';
    isLayoutNode = true;
    isCustomMultiChild = true;

    // 자식 좌표를 보고 방향 추론
    double minX = double.infinity, maxX = -double.infinity;
    double minY = double.infinity, maxY = -double.infinity;
    int peekCount = 0;
    node.visitChildren((child) {
      if (child is RenderBox && child.hasSize) {
        try {
          final o = child.localToGlobal(Offset.zero);
          if (o.dx < minX) minX = o.dx;
          if (o.dx > maxX) maxX = o.dx;
          if (o.dy < minY) minY = o.dy;
          if (o.dy > maxY) maxY = o.dy;
          peekCount++;
        } catch (_) {}
      }
    });

    if (peekCount >= 2) {
      final xRange = maxX - minX;
      final yRange = maxY - minY;
      layoutMode = xRange > yRange ? 'ROW' : 'COLUMN';
    } else {
      layoutMode = 'ROW';
    }

    if (layoutMode == 'ROW') {
      containerLayout['mainAxisAlignment'] = 'spaceBetween';
      containerLayout['crossAxisAlignment'] = 'center';
      containerLayout['mainAxisSize'] = 'max';
    } else {
      containerLayout['mainAxisAlignment'] = 'start';
      containerLayout['crossAxisAlignment'] = 'stretch';
      containerLayout['mainAxisSize'] = 'max';
    }
  }

  // ---------------------------------------------------
  // [10] DesignInfo overlay (TextField, Divider, Container)
  // ---------------------------------------------------
  final designInfo = _designInfoByRenderObject[node];
  if (designInfo != null) {
    if (designInfo.backgroundColor != null) {
      visual['backgroundColor'] = _colorToHex(designInfo.backgroundColor);
      hasVisual = true;
    }
    if (designInfo.borderColor != null) {
      visual['border'] = {
        'color': _colorToHex(designInfo.borderColor),
        'width': designInfo.borderWidth ?? 1.0,
      };
      hasVisual = true;
    }
    if (designInfo.borderRadius != null) {
      visual['borderRadius'] = designInfo.borderRadius;
    }
    if (designInfo.elevation != null && designInfo.elevation! > 0) {
      visual['shadow'] = {'elevation': designInfo.elevation};
    }
    if (designInfo.isTextField) visual['isTextField'] = true;
    if (designInfo.isDivider) visual['isDivider'] = true;
  }

  // ---------------------------------------------------
  // [10.5] TextField 구조 재편 플래그
  // ---------------------------------------------------
  final bool isTextFieldNode = visual['isTextField'] == true;

  // ---------------------------------------------------
  // [11] 자식 순회
  // ---------------------------------------------------
  final List<Map<String, dynamic>> children = [];
  final bool isFlex = node is RenderFlex;
  final bool isStack = node is RenderStack;
  final List<double> _gaps = [];
  final List<double> _childMainAxisPositions = [];

  try {
    node.visitChildren((child) {
      if (child is RenderBox) {
        final c = _crawl(child);
        if (c != null) {
          // Flex 자식: childLayout 설정
          if (isFlex) {
            final flexNode = node as RenderFlex;
            final isHorizontal = flexNode.direction == Axis.horizontal;
            final childLayout = c['childLayout'] as Map<String, dynamic>? ?? {};

            final parentData = child.parentData;
            if (parentData is FlexParentData) {
              final flex = parentData.flex ?? 0;
              final isTight = parentData.fit == FlexFit.tight;

              if (flex > 0 && isTight) {
                // Expanded
                childLayout['flexGrow'] = flex;
                if (isHorizontal) {
                  childLayout['sizingH'] = 'FILL';
                  childLayout['sizingV'] = 'HUG';
                } else {
                  childLayout['sizingH'] = 'HUG';
                  childLayout['sizingV'] = 'FILL';
                }
              } else if (flex > 0) {
                // Flexible (loose)
                childLayout['flexGrow'] = flex;
                childLayout['sizingH'] = 'HUG';
                childLayout['sizingV'] = 'HUG';
              } else {
                // 일반 자식
                childLayout['flexGrow'] = 0;
                childLayout['sizingH'] = 'HUG';
                childLayout['sizingV'] = 'HUG';
              }
            } else {
              childLayout['flexGrow'] = 0;
              childLayout['sizingH'] = 'HUG';
              childLayout['sizingV'] = 'HUG';
            }

            // crossAxisAlignment == stretch → cross축 FILL
            if (flexNode.crossAxisAlignment == CrossAxisAlignment.stretch) {
              if (isHorizontal) {
                childLayout['sizingV'] = 'FILL';
                childLayout['alignSelf'] = 'STRETCH';
              } else {
                childLayout['sizingH'] = 'FILL';
                childLayout['alignSelf'] = 'STRETCH';
              }
            }

            c['childLayout'] = childLayout;

            // itemSpacing 계산용 좌표 수집
            try {
              final childOffset = child.localToGlobal(Offset.zero);
              if (isHorizontal) {
                _childMainAxisPositions.add(childOffset.dx);
              } else {
                _childMainAxisPositions.add(childOffset.dy);
              }
            } catch (_) {}
          }

          // Stack 자식: positioned 정보 추출
          if (isStack) {
            final childLayout = c['childLayout'] as Map<String, dynamic>? ?? {};
            final parentData = child.parentData;
            if (parentData is StackParentData) {
              final pos = <String, dynamic>{};
              if (parentData.top != null) pos['top'] = parentData.top;
              if (parentData.left != null) pos['left'] = parentData.left;
              if (parentData.right != null) pos['right'] = parentData.right;
              if (parentData.bottom != null) pos['bottom'] = parentData.bottom;
              if (pos.isNotEmpty) {
                childLayout['positioned'] = pos;
              }
            }
            childLayout['sizingH'] = 'FIXED';
            childLayout['sizingV'] = 'FIXED';
            c['childLayout'] = childLayout;
          }

          children.add(c);
        }
      } else {
        // SliverPadding 감지 → padding + layout 설정
        _extractSliverPadding(child, containerLayout);
        if (containerLayout.containsKey('padding') && layoutMode == 'NONE') {
          layoutMode = 'COLUMN';
          isLayoutNode = true;
          containerLayout['crossAxisAlignment'] = 'stretch';
          containerLayout['mainAxisAlignment'] = 'start';
        }
        children.addAll(_crawlThroughSliver(child));
      }
    });
  } catch (_) {}

  // CustomMultiChildLayout: 자식을 위치 기준으로 정렬
  if (isCustomMultiChild && children.length >= 2) {
    if (layoutMode == 'COLUMN') {
      children.sort((a, b) {
        final ay = (a['rect'] as Map<String, dynamic>?)?['y'] as double? ?? 0.0;
        final by = (b['rect'] as Map<String, dynamic>?)?['y'] as double? ?? 0.0;
        return ay.compareTo(by);
      });
    } else {
      children.sort((a, b) {
        final ax = (a['rect'] as Map<String, dynamic>?)?['x'] as double? ?? 0.0;
        final bx = (b['rect'] as Map<String, dynamic>?)?['x'] as double? ?? 0.0;
        return ax.compareTo(bx);
      });
    }
  }

  // AppBar 패턴: ROW + 3자식 → leading(FILL) + title(HUG) + action(FILL)
  // 타이틀이 항상 정중앙에 오도록 leading/action이 남은 공간을 균등 분할
  if (isCustomMultiChild && layoutMode == 'ROW' && children.length == 3) {
    // leading (첫 번째) → FILL, 내용 왼쪽 정렬
    final leadCl = children[0]['childLayout'] as Map<String, dynamic>? ?? {};
    leadCl['flexGrow'] = 1;
    leadCl['sizingH'] = 'FILL';
    children[0]['childLayout'] = leadCl;

    // title (가운데) → flexGrow 0 (자연 크기)
    final titleCl = children[1]['childLayout'] as Map<String, dynamic>? ?? {};
    titleCl['flexGrow'] = 0;
    children[1]['childLayout'] = titleCl;

    // action (마지막) → FILL, 내용 오른쪽 정렬
    final actionCl = children[2]['childLayout'] as Map<String, dynamic>? ?? {};
    actionCl['flexGrow'] = 1;
    actionCl['sizingH'] = 'FILL';
    children[2]['childLayout'] = actionCl;

    // action 프레임 내부 정렬을 end로 변경
    final actionContainer = children[2]['containerLayout'] as Map<String, dynamic>? ?? {};
    actionContainer['mainAxisAlignment'] = 'end';
    children[2]['containerLayout'] = actionContainer;

    // spaceBetween → center (FILL이 공간 분배를 담당)
    containerLayout['mainAxisAlignment'] = 'center';
  }

  // ---------------------------------------------------
  // [10.5] TextField 구조 재편: bg를 입력 영역에만, 패딩 적용
  // ---------------------------------------------------
  if (isTextFieldNode && children.isNotEmpty) {
    // decoration box 찾기: 빈 Frame, 부모와 비슷한 너비
    int decoIdx = -1;
    for (int i = children.length - 1; i >= 0; i--) {
      final c = children[i];
      if (c['type'] == 'Frame' &&
          (c['children'] as List?)?.isEmpty == true) {
        final cr = c['rect'] as Map<String, dynamic>?;
        if (cr != null) {
          final cw = (cr['w'] as num?)?.toDouble() ?? 0;
          if (cw >= node.size.width * 0.9) {
            decoIdx = i;
            break;
          }
        }
      }
    }

    if (decoIdx >= 0) {
      final decoBox = children[decoIdx];
      final decoRect = decoBox['rect'] as Map<String, dynamic>;
      final decoY = (decoRect['y'] as num).toDouble();
      final decoH = (decoRect['h'] as num).toDouble();
      final decoW = (decoRect['w'] as num).toDouble();
      final decoBottom = decoY + decoH;

      // 자식을 입력 영역 안 vs 아래(에러/헬퍼)로 분리
      final List<Map<String, dynamic>> inputChildren = [];
      final List<Map<String, dynamic>> belowChildren = [];
      for (int i = 0; i < children.length; i++) {
        if (i == decoIdx) continue;
        final c = children[i];
        final cy = ((c['rect'] as Map?)?['y'] as num?)?.toDouble() ?? 0;
        if (cy >= decoBottom - 1) {
          belowChildren.add(c);
        } else {
          inputChildren.add(c);
        }
      }

      // contentPadding 계산 (첫 번째 콘텐츠 자식 좌표 기반)
      Map<String, dynamic>? paddingMap;
      for (final ic in inputChildren) {
        final icRect = ic['rect'] as Map<String, dynamic>?;
        if (icRect != null) {
          final icX = (icRect['x'] as num?)?.toDouble() ?? 0;
          final icY = (icRect['y'] as num?)?.toDouble() ?? 0;
          final icW = (icRect['w'] as num?)?.toDouble() ?? 0;
          final icH = (icRect['h'] as num?)?.toDouble() ?? 0;
          final padLeft = icX - (decoRect['x'] as num).toDouble();
          final padTop = icY - decoY;
          final padRight = decoW - padLeft - icW;
          final padBottom = decoH - padTop - icH;
          if (padLeft >= 0 && padTop >= 0) {
            paddingMap = {
              'top': padTop > 0 ? padTop : 0.0,
              'right': padRight > 0 ? padRight : 0.0,
              'bottom': padBottom > 0 ? padBottom : 0.0,
              'left': padLeft > 0 ? padLeft : 0.0,
            };
            break;
          }
        }
      }

      if (belowChildren.isNotEmpty) {
        // 에러/헬퍼 텍스트 있음 → 구조 재편
        // bg/border를 decoBox로 이동
        decoBox['visual'] = Map<String, dynamic>.from(visual);
        decoBox['children'] = inputChildren;
        decoBox['layoutMode'] = 'COLUMN';
        decoBox['containerLayout'] = <String, dynamic>{
          'mainAxisAlignment': 'center',
          'crossAxisAlignment': 'start',
          'mainAxisSize': 'min',
        };
        if (paddingMap != null) {
          (decoBox['containerLayout'] as Map<String, dynamic>)['padding'] =
              paddingMap;
        }

        // 외부 → 투명 COLUMN
        visual.clear();
        hasVisual = false;
        layoutMode = 'COLUMN';
        isLayoutNode = true;
        containerLayout['mainAxisAlignment'] = 'start';
        containerLayout['crossAxisAlignment'] = 'stretch';
        containerLayout['mainAxisSize'] = 'min';
        containerLayout['itemSpacing'] = 4.0;

        children.clear();
        children.add(decoBox);
        children.addAll(belowChildren);
      } else {
        // 에러 없음 → 현재 노드에 패딩 + 레이아웃 적용
        layoutMode = 'COLUMN';
        isLayoutNode = true;
        containerLayout['mainAxisAlignment'] = 'center';
        containerLayout['crossAxisAlignment'] = 'start';
        containerLayout['mainAxisSize'] = 'min';
        if (paddingMap != null) {
          containerLayout['padding'] = paddingMap;
        }
        children.removeAt(decoIdx);
      }
    }
  }

  // Flex: itemSpacing 계산 (개별 gap 측정 → 가장 빈번한 값 사용)
  if (isFlex && _childMainAxisPositions.length >= 2) {
    final flexNode = node as RenderFlex;
    final isHorizontal = flexNode.direction == Axis.horizontal;
    int childIdx = 0;
    node.visitChildren((child) {
      if (child is RenderBox && childIdx < _childMainAxisPositions.length - 1) {
        final double childEnd;
        if (isHorizontal) {
          childEnd = _childMainAxisPositions[childIdx] + child.size.width;
        } else {
          childEnd = _childMainAxisPositions[childIdx] + child.size.height;
        }
        final gap = _childMainAxisPositions[childIdx + 1] - childEnd;
        if (gap > 0) _gaps.add(gap.roundToDouble());
      }
      childIdx++;
    });
    if (_gaps.isNotEmpty) {
      // 모두 같으면 그 값, 다르면 가장 빈번한 값
      final allSame = _gaps.every((g) => g == _gaps.first);
      if (allSame) {
        containerLayout['itemSpacing'] = _gaps.first;
      } else {
        final freq = <double, int>{};
        for (final g in _gaps) freq[g] = (freq[g] ?? 0) + 1;
        double bestGap = _gaps.first;
        int bestCount = 0;
        freq.forEach((g, count) {
          if (count > bestCount) {
            bestGap = g;
            bestCount = count;
          }
        });
        containerLayout['itemSpacing'] = bestGap;
      }
    }
  }

  // 배경 이미지를 synthetic Image child로 추가
  if (backgroundImagePath != null) {
    final bgChild = <String, dynamic>{
      'type': 'Image',
      'layoutMode': 'NONE',
      'rect': {
        'x': offset.dx,
        'y': offset.dy,
        'w': node.size.width,
        'h': node.size.height,
      },
      'visual': <String, dynamic>{
        'imagePath': backgroundImagePath,
        'imageFit': backgroundImageFit ?? 'cover',
      },
      'children': <Map<String, dynamic>>[],
    };
    children.insert(0, bgChild);
  }

  // ---------------------------------------------------
  // Smart Flattening (조건 강화)
  // ---------------------------------------------------
  final bool hasPadding = containerLayout.containsKey('padding');
  if (type == 'Frame' &&
      !hasVisual &&
      !_hasVisualProps(visual) &&
      !isLayoutNode &&
      !isSizedBox &&
      layoutMode == 'NONE' &&
      !hasPadding &&
      children.length == 1) {
    return children.first;
  }
  if (children.isEmpty &&
      !hasVisual &&
      !_hasVisualProps(visual) &&
      (node.size.width < 1 && node.size.height < 1)) {
    return null;
  }

  // ---------------------------------------------------
  // Visual Merge + Flatten: NONE 래퍼(DecoratedBox 등)의 visual을
  // 자식 Frame에 병합하여 auto-layout 체인 유지
  // ---------------------------------------------------
  if (type == 'Frame' &&
      layoutMode == 'NONE' &&
      !isLayoutNode &&
      children.length == 1 &&
      children.first['type'] == 'Frame') {
    final child = children.first;
    final childRect = child['rect'] as Map<String, dynamic>?;
    final childW = (childRect?['w'] as num?)?.toDouble() ?? 0;
    final childH = (childRect?['h'] as num?)?.toDouble() ?? 0;

    // 자식이 부모보다 유의미하게 작으면 → merge하지 않고 센터링 컨테이너로 전환
    if ((node.size.width - childW).abs() > 4 ||
        (node.size.height - childH).abs() > 4) {
      layoutMode = 'COLUMN';
      isLayoutNode = true;
      containerLayout['mainAxisAlignment'] = 'center';
      containerLayout['crossAxisAlignment'] = 'center';
      containerLayout['mainAxisSize'] = 'max';
      // fall through → 일반 노드로 반환
    } else {
      // 같은 크기 → 기존 visual merge
      final childVisual = child['visual'] as Map<String, dynamic>;

      // outer visual → child에 병합 (child 기존 값 우선)
      visual.forEach((key, value) {
        if (value != null && !childVisual.containsKey(key)) {
          childVisual[key] = value;
        }
      });

      // outer rect 유지 (바운딩 박스)
      child['rect'] = {
        'x': offset.dx,
        'y': offset.dy,
        'w': node.size.width,
        'h': node.size.height,
      };
      return child;
    }
  }

  // Debug: layoutMode가 NONE인 노드 상세 로깅
  if (layoutMode == 'NONE') {
    print('[CRAWL-DEBUG] layoutMode=NONE with ${children.length} children');
    print('  runtimeType: ${node.runtimeType}');
    print('  runtimeTypeStr: $runtimeTypeStr');
    print('  size: ${node.size}');
    print('  hasVisual: $hasVisual');
    print('  isLayoutNode: $isLayoutNode');
    print('  isSizedBox: $isSizedBox');
    print('  visual keys: ${visual.keys.toList()}');
    print('  containerLayout: $containerLayout');
    try {
      final parent = node.parent;
      if (parent != null) {
        print('  parent runtimeType: ${parent.runtimeType}');
      }
    } catch (_) {}
    for (int i = 0; i < children.length; i++) {
      final c = children[i];
      print(
        '  child[$i]: type=${c['type']}, layoutMode=${c['layoutMode']}, '
        'rect=${c['rect']}',
      );
    }
  }

  // ---------------------------------------------------
  // 최종 노드 반환 (새 스키마)
  // ---------------------------------------------------
  final result = <String, dynamic>{
    'type': type,
    'layoutMode': layoutMode,
    'rect': {
      'x': offset.dx,
      'y': offset.dy,
      'w': node.size.width,
      'h': node.size.height,
    },
    'visual': visual,
    'children': children,
  };
  if (containerLayout.isNotEmpty) result['containerLayout'] = containerLayout;
  // childLayout은 부모가 설정 (위에서 이미 설정됨)
  return result;
}

/// =======================================================
/// 4. 겹친 화면 제거
/// =======================================================

List<Map<String, dynamic>> _filterOverlappingScreens(
  List<Map<String, dynamic>> items,
  ui.Size screenSize,
) {
  if (items.isEmpty) return items;
  List<int> fullScreenIndices = [];
  for (int i = 0; i < items.length; i++) {
    final rect = items[i]['rect'];
    if (rect != null) {
      double w = (rect['w'] as num?)?.toDouble() ?? 0.0;
      double h = (rect['h'] as num?)?.toDouble() ?? 0.0;
      if (w >= screenSize.width * 0.8 && h >= screenSize.height * 0.8) {
        fullScreenIndices.add(i);
      }
    }
  }
  if (fullScreenIndices.length > 1) {
    int topMostIndex = fullScreenIndices.last;
    List<Map<String, dynamic>> result = [];
    for (int i = 0; i < items.length; i++) {
      if (fullScreenIndices.contains(i) && i != topMostIndex) continue;
      result.add(items[i]);
    }
    return result;
  }
  return items;
}

/// =======================================================
/// 5. 외부 진입점
/// =======================================================

String figmaExtractorEntryPoint() {
  try {
    debugPrint('[FigmaCrawler] ===== START (v2) =====');
    _designInfoByRenderObject.clear();
    _svgBoxTargets.clear();

    final rootElement = WidgetsBinding.instance.renderViewElement;
    if (rootElement != null) {
      try {
        rootElement.visitChildren(_collectDesignInfoFromElements);
      } catch (e, st) {
        debugPrint('[FigmaCrawler] Step 1 ERROR: $e\n$st');
      }
    }

    final root = RendererBinding.instance.renderView;
    final List<Map<String, dynamic>> rootChildren = [];
    root.visitChildren((child) {
      final res = _crawl(child);
      if (res != null) rootChildren.add(res);
    });

    double maxWidth = 0.0;
    double maxHeight = 0.0;
    try {
      maxWidth = root.size.width;
      maxHeight = root.size.height;
    } catch (_) {}

    final ui.Size screenSize = ui.Size(
      maxWidth > 0 ? maxWidth : 390.0,
      maxHeight > 0 ? maxHeight : 844.0,
    );

    final filteredChildren = _filterOverlappingScreens(
      rootChildren,
      screenSize,
    );

    final data = {
      'type': 'Frame',
      'name': 'Flutter Screen',
      'layoutMode': 'COLUMN',
      'rect': {
        'x': 0.0,
        'y': 0.0,
        'w': screenSize.width,
        'h': screenSize.height,
      },
      'visual': {'backgroundColor': '#ffffffff'},
      'containerLayout': {
        'mainAxisAlignment': 'start',
        'crossAxisAlignment': 'stretch',
        'mainAxisSize': 'max',
        'itemSpacing': 0.0,
        'padding': {'top': 0.0, 'right': 0.0, 'bottom': 0.0, 'left': 0.0},
      },
      'children': filteredChildren,
    };

    final result = jsonEncode(data);
    debugPrint('[FigmaCrawler] ===== DONE (${result.length} chars) =====');
    return result;
  } catch (e, st) {
    debugPrint('[FigmaCrawler] FATAL ERROR: $e\n$st');
    return jsonEncode({'error': e.toString(), 'stackTrace': st.toString()});
  }
}

/// =======================================================
/// 6. Async export (이미지 pre-capture 포함)
/// =======================================================

Future<String> _figmaExportWithImagesAsync() async {
  _imageDataByNode.clear();

  final root = RendererBinding.instance.renderView;

  // Phase 1: async pre-capture
  await _preCaptureImages(root);

  // Phase 2: 기존 sync 크롤 (figmaExtractorEntryPoint 재사용)
  final result = figmaExtractorEntryPoint();

  _imageDataByNode.clear(); // 메모리 해제
  return result;
}

/// CLI에서 호출: evaluate('figmaStartExportWithImages()')
void figmaStartExportWithImages() {
  _asyncExportBusy = true;
  _asyncExportResult = null;
  _figmaExportWithImagesAsync().then((r) {
    _asyncExportResult = r;
    _asyncExportBusy = false;
  }).catchError((e) {
    _asyncExportResult = '{"error":"$e"}';
    _asyncExportBusy = false;
  });
}

/// CLI에서 폴링: evaluate('figmaGetExportResult()')
String? figmaGetExportResult() {
  if (_asyncExportBusy) return null;
  return _asyncExportResult;
}
