#!/usr/bin/env dart
// tools/export_figma_layout.dart
//
// Pure Dart CLI — 외부 패키지 의존성 0개, 크롤러 소스 내장
// 실행 중인 Flutter 앱에서 레이아웃 JSON을 추출합니다.
//
// 사용법:
//   dart tools/export_figma_layout.dart                  ← VM Service 자동 탐지
//   dart tools/export_figma_layout.dart ws://...         ← 수동 URI 지정
//
// Android Studio External Tool 설정:
//   Program:           dart
//   Arguments:         /path/to/tools/export_figma_layout.dart
//   Working directory: $ProjectFileDir$

import 'dart:async';
import 'dart:convert';
import 'dart:io';

// =============================================================
// 임베디드 크롤러 소스 (figma_exporter_inject.dart)
// =============================================================

const _crawlerSource = r"""
// figma_temp_crawler.dart (auto-generated by export_figma_layout.dart)

import 'dart:convert';
import 'dart:ui' as ui;
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';

/// =======================================================
/// 0. 유틸 & 전역 상태
/// =======================================================

String? _colorToHex(Color? color) {
  if (color == null) return null;
  return '#' + color.value.toRadixString(16).padLeft(8, '0');
}

class DesignInfo {
  final Color? backgroundColor;
  final Color? borderColor;
  final double? borderWidth;
  final double? borderRadius;
  final double? elevation;
  final bool isTextField;
  final bool isDivider;

  DesignInfo({
    this.backgroundColor,
    this.borderColor,
    this.borderWidth,
    this.borderRadius,
    this.elevation,
    this.isTextField = false,
    this.isDivider = false,
  });
}

final Map<RenderObject, DesignInfo> _designInfoByRenderObject = {};
final Set<RenderObject> _svgBoxTargets = {};

/// =======================================================
/// 1. Element 트리 순회해서 위젯 레벨 디자인 정보 수집
/// =======================================================

void _collectDesignInfoFromElements(Element element) {
  final widget = element.widget;

  if (widget is InputDecorator) {
    final InputDecoration deco = widget.decoration;
    Color? bg;
    Color? borderColor;
    double? borderWidth;
    double? radius;

    if (deco.filled == true) {
      bg = deco.fillColor;
    }

    final InputBorder? border =
        deco.enabledBorder ?? deco.focusedBorder ?? deco.border;

    if (border is OutlineInputBorder) {
      final side = border.borderSide;
      borderColor = side.color;
      borderWidth = side.width;
      final br = border.borderRadius;
      if (br is BorderRadius) {
        radius = br.topLeft.x;
      }
    }

    final ro = element.renderObject;
    if (ro != null && (bg != null || borderColor != null || radius != null)) {
      _designInfoByRenderObject[ro] = DesignInfo(
        backgroundColor: bg,
        borderColor: borderColor,
        borderWidth: borderWidth,
        borderRadius: radius,
        isTextField: true,
      );
    }
  }

  if (widget is Divider) {
    final ro = element.renderObject;
    if (ro != null && widget.color != null) {
      _designInfoByRenderObject[ro] = DesignInfo(
        backgroundColor: widget.color,
        isDivider: true,
      );
    }
  }

  if (widget is Container) {
    final deco = widget.decoration;
    Color? bg;
    Color? borderColor;
    double? borderWidth;
    double? radius;

    if (deco is BoxDecoration) {
      bg = deco.color;
      final border = deco.border;
      if (border is Border) {
        final side = border.top;
        borderColor = side.color;
        borderWidth = side.width;
      }
      final br = deco.borderRadius;
      if (br is BorderRadius) {
        radius = br.topLeft.x;
      }
    }

    final ro = element.renderObject;
    if (ro != null && (bg != null || borderColor != null)) {
      _designInfoByRenderObject[ro] = DesignInfo(
        backgroundColor: bg,
        borderColor: borderColor,
        borderWidth: borderWidth,
        borderRadius: radius,
      );
    }
  }

  if (widget.runtimeType.toString().contains('SvgPicture')) {
    final ro = element.renderObject;
    if (ro != null) {
      _svgBoxTargets.add(ro);
    }
  }

  element.visitChildren(_collectDesignInfoFromElements);
}

/// =======================================================
/// 2. Render 트리 크롤러
/// =======================================================

List<Map<String, dynamic>> _crawlThroughSliver(RenderObject sliver) {
  final List<Map<String, dynamic>> results = [];
  sliver.visitChildren((child) {
    if (child is RenderBox) {
      final res = _crawl(child);
      if (res != null) results.add(res);
    } else {
      results.addAll(_crawlThroughSliver(child));
    }
  });
  return results;
}

Map<String, dynamic>? _crawl(RenderObject? node) {
  if (node == null) return null;

  if (node is! RenderBox) {
    final sliverChildren = _crawlThroughSliver(node);
    if (sliverChildren.isEmpty) return null;
    if (sliverChildren.length == 1) return sliverChildren.first;
    return {
      'type': 'Frame',
      'rect': sliverChildren.first['rect'],
      'properties': <String, dynamic>{},
      'children': sliverChildren,
    };
  }

  if (!node.hasSize) return null;
  if (node.size.width == 0 && node.size.height == 0) return null;

  if (node is RenderOffstage && node.offstage) {
    return null;
  }

  Offset offset;
  try {
    offset = node.localToGlobal(Offset.zero);
  } catch (_) {
    return null;
  }

  String type = 'Frame';
  final Map<String, dynamic> props = {};
  bool hasVisualProperty = false;
  bool isLayoutNode = false;

  final String runtimeTypeStr = node.runtimeType.toString();
  final bool isSvgBoxTarget = _svgBoxTargets.contains(node);

  String? backgroundImagePath;
  String? backgroundImageFit;

  // [0] SvgPicture placeholder
  if (isSvgBoxTarget) {
    type = 'Frame';
    hasVisualProperty = true;
    props['backgroundColor'] = '#ffdddddd';
    props['isSvgBox'] = true;
  }

  // [1] Text / Icon
  else if (node is RenderParagraph) {
    TextStyle? style;
    InlineSpan inlineSpan = node.text;
    if (inlineSpan is TextSpan) {
      style = inlineSpan.style;
    }
    final String? fontFamily = style?.fontFamily;

    if (fontFamily != null && fontFamily.contains('MaterialIcons')) {
      type = 'Frame';
      hasVisualProperty = true;
      final Color color = style?.color ?? const Color(0xFF000000);
      props['backgroundColor'] = _colorToHex(color);
      props['isIconBox'] = true;
      props['iconFontFamily'] = fontFamily;
      props['iconGlyph'] = node.text.toPlainText();
    } else {
      type = 'Text';
      hasVisualProperty = true;
      try {
        props['content'] = node.text.toPlainText();
        props['textAlign'] = node.textAlign.toString();
        if (style != null) {
          props['fontFamily'] = style.fontFamily;
          props['fontSize'] = style.fontSize;
          props['fontWeight'] = style.fontWeight.toString();
          props['color'] = _colorToHex(style.color);
          props['letterSpacing'] = style.letterSpacing;
        }
      } catch (_) {}
    }
  }

  // [2] Image
  else if (node is RenderImage) {
    type = 'Image';
    hasVisualProperty = true;
    try {
      props['imagePath'] = node.debugImageLabel;
      props['fit'] = 'cover';
    } catch (_) {}
  }

  // [2.5] Padding (RenderPadding)
  else if (node is RenderPadding) {
    final EdgeInsetsGeometry resolvedPadding = node.padding;
    EdgeInsets insets;
    if (resolvedPadding is EdgeInsets) {
      insets = resolvedPadding;
    } else {
      insets = resolvedPadding.resolve(TextDirection.ltr);
    }

    RenderBox? singleChild;
    int childCount = 0;
    node.visitChildren((child) {
      childCount++;
      if (child is RenderBox) singleChild = child;
    });

    if (childCount == 1 && singleChild is RenderFlex) {
      final flexResult = _crawl(singleChild);
      if (flexResult != null) {
        final flexProps = flexResult['properties'] as Map<String, dynamic>;
        flexProps['paddingTop'] = insets.top;
        flexProps['paddingRight'] = insets.right;
        flexProps['paddingBottom'] = insets.bottom;
        flexProps['paddingLeft'] = insets.left;
        flexResult['rect'] = {
          'x': offset.dx,
          'y': offset.dy,
          'w': node.size.width,
          'h': node.size.height,
        };
        return flexResult;
      }
    }

    type = 'Frame';
    isLayoutNode = true;
    props['paddingTop'] = insets.top;
    props['paddingRight'] = insets.right;
    props['paddingBottom'] = insets.bottom;
    props['paddingLeft'] = insets.left;
  }

  // [3] Flex (Row / Column)
  else if (node is RenderFlex) {
    type = 'Frame';
    isLayoutNode = true;
    props['layoutMode'] =
        node.direction == Axis.horizontal ? 'HORIZONTAL' : 'VERTICAL';
    props['mainAxisAlignment'] = node.mainAxisAlignment.toString();
    props['crossAxisAlignment'] = node.crossAxisAlignment.toString();
    props['mainAxisSize'] = node.mainAxisSize == MainAxisSize.min ? 'AUTO' : 'FIXED';
  }

  // [4] DecoratedBox
  else if (node is RenderDecoratedBox) {
    type = 'Frame';
    try {
      final decoration = node.decoration;
      if (decoration is BoxDecoration) {
        if (decoration.color != null) {
          props['backgroundColor'] = _colorToHex(decoration.color);
          hasVisualProperty = true;
        }
        if (decoration.image != null) {
          final DecorationImage decorationImage = decoration.image!;
          final ImageProvider provider = decorationImage.image;
          if (provider is AssetImage) {
            backgroundImagePath = provider.assetName;
            backgroundImageFit = decorationImage.fit?.toString();
            hasVisualProperty = true;
          }
        }
        if (decoration.border != null) {
          final border = decoration.border;
          if (border is Border) {
            final sides = [border.top, border.right, border.bottom, border.left];
            BorderSide? bestSide;
            for (final side in sides) {
              if (side.width > 0) { bestSide = side; break; }
            }
            if (bestSide != null) {
              props['hasBorder'] = true;
              props['borderWidth'] = bestSide.width;
              props['borderColor'] = _colorToHex(bestSide.color);
              hasVisualProperty = true;
            }
          } else {
            props['hasBorder'] = true;
            hasVisualProperty = true;
          }
        }
        if (decoration.borderRadius != null) {
          props['borderRadius'] = decoration.borderRadius.toString();
        }
        if (decoration.boxShadow != null && decoration.boxShadow!.isNotEmpty) {
          props['hasShadow'] = true;
          hasVisualProperty = true;
        }
      }
    } catch (_) {}
  }

  // [5] PhysicalModel
  else if (node is RenderPhysicalModel) {
    type = 'Frame';
    hasVisualProperty = true;
    props['backgroundColor'] = _colorToHex(node.color);
    if (node.elevation > 0) {
      props['hasShadow'] = true;
      props['elevation'] = node.elevation;
    }
    try {
      dynamic d = node;
      if (d.borderRadius != null) {
        props['borderRadius'] = d.borderRadius.toString();
      }
    } catch (_) {}
  }

  // [6] PhysicalShape
  else if (node is RenderPhysicalShape) {
    type = 'Frame';
    hasVisualProperty = true;
    props['backgroundColor'] = _colorToHex(node.color);
    if (node.elevation > 0) {
      props['hasShadow'] = true;
      props['elevation'] = node.elevation;
    }
    try {
      final diagnostics = node.toDiagnosticsNode();
      final properties = diagnostics.getProperties();
      final clipperProp = properties.firstWhere(
        (p) => p.name == 'clipper',
        orElse: () => DiagnosticsProperty('dummy', null),
      );
      if (clipperProp.value != null) {
        dynamic clipper = clipperProp.value;
        dynamic shape = clipper.shape;
        final shapeStr = shape.toString();
        final reg = RegExp(r'circular\(([\d\.]+)\)');
        final m = reg.firstMatch(shapeStr);
        if (m != null) {
          props['borderRadius'] = m.group(1);
        } else {
          props['isCustomShape'] = true;
        }
      } else {
        props['isCustomShape'] = true;
      }
    } catch (_) {
      props['isCustomShape'] = true;
    }
  }

  // [7] Picture / CustomPaint
  else if (runtimeTypeStr.contains('Picture') ||
      runtimeTypeStr.contains('CustomPaint')) {
    type = 'Frame';
    props['isVectorCandidate'] = true;
    hasVisualProperty = false;
  }

  // [8] DesignInfo overlay
  final designInfo = _designInfoByRenderObject[node];
  if (designInfo != null) {
    if (designInfo.backgroundColor != null) {
      props['backgroundColor'] = _colorToHex(designInfo.backgroundColor);
      hasVisualProperty = true;
    }
    if (designInfo.borderColor != null) {
      props['borderColor'] = _colorToHex(designInfo.borderColor);
      props['hasBorder'] = true;
      if (designInfo.borderWidth != null) props['borderWidth'] = designInfo.borderWidth;
      hasVisualProperty = true;
    }
    if (designInfo.borderRadius != null) {
      props['borderRadius'] = designInfo.borderRadius.toString();
    }
    if (designInfo.elevation != null) {
      props['elevation'] = designInfo.elevation;
      if (designInfo.elevation! > 0) props['hasShadow'] = true;
    }
    if (designInfo.isTextField) props['isTextField'] = true;
    if (designInfo.isDivider) props['isDivider'] = true;
  }

  // [9] 자식 순회
  final List<Map<String, dynamic>> children = [];
  final bool isFlex = node is RenderFlex;
  final List<double> _childMainAxisPositions = [];

  try {
    node.visitChildren((child) {
      if (child is RenderBox) {
        final c = _crawl(child);
        if (c != null) {
          if (isFlex) {
            final parentData = child.parentData;
            if (parentData is FlexParentData) {
              final childProps = c['properties'] as Map<String, dynamic>;
              if (parentData.flex != null && parentData.flex! > 0) {
                childProps['flexGrow'] = parentData.flex;
                childProps['flexFit'] = parentData.fit.toString();
              }
            }
            try {
              final childOffset = child.localToGlobal(Offset.zero);
              final flexNode = node as RenderFlex;
              if (flexNode.direction == Axis.horizontal) {
                _childMainAxisPositions.add(childOffset.dx);
              } else {
                _childMainAxisPositions.add(childOffset.dy);
              }
            } catch (_) {}
          }
          children.add(c);
        }
      } else {
        children.addAll(_crawlThroughSliver(child));
      }
    });
  } catch (_) {}

  // Flex: itemSpacing 계산
  if (isFlex && _childMainAxisPositions.length >= 2) {
    final flexNode = node as RenderFlex;
    double totalGap = 0;
    int gapCount = 0;
    int childIdx = 0;
    node.visitChildren((child) {
      if (child is RenderBox && childIdx < _childMainAxisPositions.length - 1) {
        final double childEnd;
        if (flexNode.direction == Axis.horizontal) {
          childEnd = _childMainAxisPositions[childIdx] + child.size.width;
        } else {
          childEnd = _childMainAxisPositions[childIdx] + child.size.height;
        }
        final gap = _childMainAxisPositions[childIdx + 1] - childEnd;
        if (gap > 0) { totalGap += gap; gapCount++; }
      }
      childIdx++;
    });
    if (gapCount > 0) {
      props['itemSpacing'] = (totalGap / gapCount).roundToDouble();
    }
  }

  // [9.5] 배경 이미지를 synthetic Image child로 추가
  if (backgroundImagePath != null) {
    final bgChild = <String, dynamic>{
      'type': 'Image',
      'rect': { 'x': offset.dx, 'y': offset.dy, 'w': node.size.width, 'h': node.size.height },
      'properties': <String, dynamic>{
        'imagePath': backgroundImagePath,
        'fit': backgroundImageFit ?? 'BoxFit.cover',
        'isBackgroundImage': true,
      },
      'children': <Map<String, dynamic>>[],
    };
    children.insert(0, bgChild);
  }

  // [10] Smart Flattening
  if (type == 'Frame' && !hasVisualProperty && !isLayoutNode && children.length == 1) {
    return children.first;
  }
  if (children.isEmpty && !hasVisualProperty && (node.size.width < 1 && node.size.height < 1)) {
    return null;
  }

  return {
    'type': type,
    'rect': { 'x': offset.dx, 'y': offset.dy, 'w': node.size.width, 'h': node.size.height },
    'properties': props,
    'children': children,
  };
}

/// =======================================================
/// 2.5. 겹친 화면 제거
/// =======================================================

List<Map<String, dynamic>> _filterOverlappingScreens(
    List<Map<String, dynamic>> items, ui.Size screenSize) {
  if (items.isEmpty) return items;
  List<int> fullScreenIndices = [];
  for (int i = 0; i < items.length; i++) {
    final rect = items[i]['rect'];
    if (rect != null) {
      double w = (rect['w'] as num?)?.toDouble() ?? 0.0;
      double h = (rect['h'] as num?)?.toDouble() ?? 0.0;
      if (w >= screenSize.width * 0.8 && h >= screenSize.height * 0.8) {
        fullScreenIndices.add(i);
      }
    }
  }
  if (fullScreenIndices.length > 1) {
    int topMostIndex = fullScreenIndices.last;
    List<Map<String, dynamic>> result = [];
    for (int i = 0; i < items.length; i++) {
      if (fullScreenIndices.contains(i) && i != topMostIndex) continue;
      result.add(items[i]);
    }
    return result;
  }
  return items;
}

/// =======================================================
/// 3. 외부 진입점
/// =======================================================

String figmaExtractorEntryPoint() {
  try {
    debugPrint('[FigmaCrawler] ===== START =====');
    _designInfoByRenderObject.clear();
    _svgBoxTargets.clear();

    final rootElement = WidgetsBinding.instance.renderViewElement;
    if (rootElement != null) {
      try {
        rootElement.visitChildren(_collectDesignInfoFromElements);
      } catch (e, st) {
        debugPrint('[FigmaCrawler] Step 1 ERROR: $e\n$st');
      }
    }

    final root = RendererBinding.instance.renderView;
    final List<Map<String, dynamic>> rootChildren = [];
    root.visitChildren((child) {
      final res = _crawl(child);
      if (res != null) rootChildren.add(res);
    });

    double maxWidth = 0.0;
    double maxHeight = 0.0;
    try { maxWidth = root.size.width; maxHeight = root.size.height; } catch (_) {}

    final ui.Size screenSize = ui.Size(
      maxWidth > 0 ? maxWidth : 390.0,
      maxHeight > 0 ? maxHeight : 844.0,
    );

    final filteredChildren = _filterOverlappingScreens(rootChildren, screenSize);

    final data = {
      'type': 'Frame',
      'name': 'Flutter Screen',
      'rect': { 'x': 0.0, 'y': 0.0, 'w': screenSize.width, 'h': screenSize.height },
      'properties': { 'backgroundColor': '#ffffffff' },
      'children': filteredChildren,
    };

    final result = jsonEncode(data);
    debugPrint('[FigmaCrawler] ===== DONE (${result.length} chars) =====');
    return result;
  } catch (e, st) {
    debugPrint('[FigmaCrawler] FATAL ERROR: $e\n$st');
    return jsonEncode({ 'error': e.toString(), 'stackTrace': st.toString() });
  }
}
""";

// =============================================================
// JSON-RPC 2.0 over WebSocket
// =============================================================

int _rpcId = 1;
final Map<int, Completer<dynamic>> _pending = {};

Future<dynamic> rpcCall(
  WebSocket ws,
  String method, [
  Map<String, dynamic>? params,
]) {
  final id = _rpcId++;
  final completer = Completer<dynamic>();
  _pending[id] = completer;

  final payload = <String, dynamic>{
    'jsonrpc': '2.0',
    'id': id,
    'method': method,
  };
  if (params != null) payload['params'] = params;

  ws.add(jsonEncode(payload));
  return completer.future.timeout(const Duration(seconds: 30));
}

void _onWsData(dynamic data) {
  try {
    final msg = jsonDecode(data as String);
    if (msg is Map<String, dynamic>) {
      final id = msg['id'];
      if (id is int && _pending.containsKey(id)) {
        final c = _pending.remove(id)!;
        if (msg.containsKey('error')) {
          c.completeError(Exception(jsonEncode(msg['error'])));
        } else {
          c.complete(msg['result']);
        }
      }
    }
  } catch (e) {
    _log('WS parse error: $e');
  }
}

// =============================================================
// 로깅
// =============================================================

void _log(String msg) => stderr.writeln(msg);

// =============================================================
// VM Service URI 자동 탐지
// =============================================================

/// Strategy 1 (가장 정확): ps에서 development-service 프로세스 찾기
/// → raw VM Service URI 추출 → HTTP redirect → DDS WS URI (토큰 포함)
Future<String?> _discoverViaDds() async {
  _log('[Discovery] ps에서 development-service 프로세스 탐색...');

  final ps = await Process.run('ps', ['-eo', 'pid,args']);
  final lines = (ps.stdout as String).split('\n');

  String? rawVmUri;
  for (final line in lines) {
    if (!line.contains('development-service')) continue;
    if (line.contains('grep')) continue;
    final match = RegExp(r'vm-service-uri=(http://[^\s]+)').firstMatch(line);
    if (match != null) {
      rawVmUri = match.group(1)!;
      _log('[Discovery] Raw VM Service URI: $rawVmUri');
      break;
    }
  }

  if (rawVmUri == null) return null;

  // HTTP GET → redirect 따라가서 DDS WS URI 얻기
  _log('[Discovery] HTTP redirect 추적 중...');
  final client = HttpClient();
  client.connectionTimeout = const Duration(seconds: 5);

  try {
    final request = await client.getUrl(Uri.parse(rawVmUri));
    request.followRedirects = false;
    final response = await request.close();
    // body 소비
    await response.drain<void>();

    _log('[Discovery] HTTP ${response.statusCode}');

    if (response.statusCode == 302 || response.statusCode == 301) {
      final redirectUrl = response.headers.value('location');
      _log('[Discovery] Redirect → $redirectUrl');
      if (redirectUrl != null) {
        final wsUri = Uri.parse(redirectUrl).queryParameters['uri'];
        if (wsUri != null) {
          _log('[Discovery] DDS WS URI: $wsUri');
          return wsUri;
        }
      }
    }
  } catch (e) {
    _log('[Discovery] HTTP 요청 실패: $e');
  } finally {
    client.close();
  }

  // redirect 실패 시 raw URI를 ws로 변환해서 시도
  var fallback = rawVmUri
      .replaceFirst('http://', 'ws://')
      .replaceFirst('https://', 'wss://');
  if (!fallback.endsWith('/ws')) {
    fallback = fallback.endsWith('/') ? '${fallback}ws' : '$fallback/ws';
  }
  _log('[Discovery] Redirect 실패 → fallback: $fallback');
  return fallback;
}

/// Strategy 2 (fallback): lsof로 Dart 프로세스 포트 스캔
Future<String?> _scanDartPorts() async {
  _log('[Discovery] lsof 포트 스캔...');
  try {
    final result = await Process.run('lsof', ['-i', '-P', '-n']);
    for (final line in (result.stdout as String).split('\n')) {
      if (!line.toLowerCase().contains('dart')) continue;
      if (!line.contains('LISTEN')) continue;
      final m = RegExp(r':(\d+)\s+\(LISTEN\)').firstMatch(line);
      if (m != null) {
        final uri = 'ws://127.0.0.1:${m.group(1)}/ws';
        _log('[Discovery] lsof에서 포트 발견: $uri');
        return uri;
      }
    }
  } catch (_) {}
  return null;
}

Future<String?> discoverVmServiceUri() async {
  _log('[Discovery] VM Service 자동 탐색 중...');

  // 1차: DDS 프로세스 → redirect → 정확한 WS URI (토큰 포함)
  final fromDds = await _discoverViaDds();
  if (fromDds != null) return fromDds;

  // 2차: lsof 포트 스캔 (토큰 없이 시도, --disable-service-auth-codes 필요)
  final fromPort = await _scanDartPorts();
  if (fromPort != null) return fromPort;

  return null;
}

// =============================================================
// 크롤러 주입 (내장 소스 → 파일 생성 + import 추가)
// =============================================================

/// 크롤러 주입. 이미 주입돼 있으면 false, 새로 주입하면 true 반환.
bool injectCrawler(String projectPath) {
  final destPath = '$projectPath/lib/figma_temp_crawler.dart';
  final mainPath = '$projectPath/lib/main.dart';

  if (!File(mainPath).existsSync()) {
    throw Exception('$mainPath 파일을 찾을 수 없습니다.');
  }

  // 내장 소스를 파일로 쓰기 (항상 최신으로 덮어쓰기)
  File(destPath).writeAsStringSync(_crawlerSource);
  _log('[Inject] 크롤러 생성 → $destPath');

  // main.dart에 import 추가
  var mainCode = File(mainPath).readAsStringSync();
  if (mainCode.contains("import 'figma_temp_crawler.dart'")) {
    _log('[Inject] import 이미 존재 → hot reload 불필요');
    return false;
  }

  final importRe = RegExp('^import\\s+[\\x27\\x22].*[\\x27\\x22];?\\s*\$', multiLine: true);
  final matches = importRe.allMatches(mainCode).toList();
  if (matches.isNotEmpty) {
    final end = matches.last.end;
    mainCode = '${mainCode.substring(0, end)}'
        "\nimport 'figma_temp_crawler.dart';\n"
        '${mainCode.substring(end)}';
  } else {
    mainCode = "import 'figma_temp_crawler.dart';\n$mainCode";
  }

  File(mainPath).writeAsStringSync(mainCode);
  _log('[Inject] main.dart에 import 추가 완료');
  return true;
}

// =============================================================
// 메인
// =============================================================

Future<void> main(List<String> args) async {
  final projectPath = Directory.current.path;
  _log('========================================');
  _log(' Flutter → Figma Layout Exporter');
  _log('========================================');
  _log('[Project] $projectPath');

  // ---- VM Service URI ----
  String? vmUri;
  if (args.isNotEmpty) {
    vmUri = args[0];
    _log('[URI] 수동 지정: $vmUri');
  } else {
    vmUri = await discoverVmServiceUri();
  }
  if (vmUri == null) {
    _log('');
    _log('[ERROR] 실행 중인 Flutter 앱을 찾을 수 없습니다.');
    _log('');
    _log('해결 방법:');
    _log('  1) Flutter 앱을 디버그 모드로 먼저 실행하세요.');
    _log('  2) 콘솔에 출력된 VM Service URI를 인자로 전달하세요:');
    _log('     dart tools/export_figma_layout.dart ws://127.0.0.1:PORT/TOKEN=/ws');
    exit(1);
  }

  // ---- 크롤러 주입 ----
  final needsReload = injectCrawler(projectPath);

  // ---- WebSocket 연결 ----
  _log('[Connect] $vmUri');
  late WebSocket ws;
  try {
    ws = await WebSocket.connect(vmUri);
  } catch (e) {
    _log('[ERROR] WebSocket 연결 실패: $e');
    _log('URI가 올바른지, Flutter 앱이 디버그 모드로 실행 중인지 확인하세요.');
    exit(1);
  }
  ws.listen(_onWsData, onError: (e) => _log('[WS ERROR] $e'));

  try {
    // ---- getVM → isolateId ----
    final vm = await rpcCall(ws, 'getVM') as Map<String, dynamic>;
    final isolates =
        (vm['isolates'] as List).cast<Map<String, dynamic>>();
    if (isolates.isEmpty) throw Exception('VM에 isolate가 없습니다.');
    final isolateId = isolates[0]['id'] as String;
    _log('[VM] isolate: $isolateId');

    // ---- Hot Reload (필요 시) ----
    if (needsReload) {
      _log('[HotReload] reloadSources 호출 중...');
      await rpcCall(ws, 'reloadSources', {'isolateId': isolateId});
      await Future.delayed(const Duration(seconds: 3));
      _log('[HotReload] 완료');
    }

    // ---- 크롤러 라이브러리 찾기 ----
    final iso = await rpcCall(ws, 'getIsolate', {'isolateId': isolateId})
        as Map<String, dynamic>;
    final libs =
        (iso['libraries'] as List).cast<Map<String, dynamic>>();
    final crawlerLib = libs.cast<Map<String, dynamic>?>().firstWhere(
          (l) => (l!['uri'] as String).contains('figma_temp_crawler'),
          orElse: () => null,
        );

    await Future.delayed(const Duration(milliseconds: 1500));

    // ---- evaluate ----
    _log('[Evaluate] figmaExtractorEntryPoint() 호출...');
    dynamic result;
    if (crawlerLib != null) {
      try {
        result = await rpcCall(ws, 'evaluate', {
          'isolateId': isolateId,
          'targetId': crawlerLib['id'],
          'expression': 'figmaExtractorEntryPoint()',
        });
      } catch (_) {
        _log('[Evaluate] 라이브러리 컨텍스트 실패 → 전역 컨텍스트 재시도');
        result = await rpcCall(ws, 'evaluate', {
          'isolateId': isolateId,
          'expression': 'figmaExtractorEntryPoint()',
        });
      }
    } else {
      result = await rpcCall(ws, 'evaluate', {
        'isolateId': isolateId,
        'expression': 'figmaExtractorEntryPoint()',
      });
    }

    // ---- 결과 추출 (truncation 처리) ----
    final res = result as Map<String, dynamic>;
    String jsonString;
    if (res['valueAsString'] != null &&
        res['valueAsStringIsTruncated'] != true) {
      jsonString = res['valueAsString'] as String;
    } else if (res['id'] != null) {
      _log('[Evaluate] 결과가 잘림 → getObject로 전체 가져오기...');
      final full = await rpcCall(ws, 'getObject', {
        'isolateId': isolateId,
        'objectId': res['id'],
      }) as Map<String, dynamic>;
      jsonString = full['valueAsString'] as String;
    } else {
      throw Exception('예상치 못한 결과: ${jsonEncode(result)}');
    }

    // ---- 저장 ----
    final dumpDir = Directory('$projectPath/flutter_figma_dump');
    if (!dumpDir.existsSync()) dumpDir.createSync(recursive: true);

    File('${dumpDir.path}/figma_layout_raw.json')
        .writeAsStringSync(jsonString);

    final data = jsonDecode(jsonString);
    final pretty = const JsonEncoder.withIndent('  ').convert(data);
    File('${dumpDir.path}/figma_layout.json').writeAsStringSync(pretty);

    // 클립보드 (macOS)
    try {
      final pb = await Process.start('pbcopy', []);
      pb.stdin.write(pretty);
      await pb.stdin.close();
      await pb.exitCode;
      _log('[Done] 클립보드에 복사 완료');
    } catch (_) {}

    _log('[Done] 저장 → flutter_figma_dump/figma_layout.json');
    _log('[Done] JSON 길이: ${jsonString.length} chars');
    _log('========================================');
  } finally {
    await ws.close();
  }
}
